#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AC_DistanceToTarget

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AC_DistanceToTarget.AC_DistanceToTarget_C
// 0x0008 (0x00E0 - 0x00D8)
class UAC_DistanceToTarget_C final : public UAIActionConsideration
{
public:
	bool                                          Allow_Last_Tracked_Target;                         // 0x00D8(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAllowEnemy;                                       // 0x00D9(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAllowFriendly;                                    // 0x00DA(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAllowNeutral;                                     // 0x00DB(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	float CalculateCurve(float X) const;
	float Score(const struct FAIActionDecisionContext& Context, bool* bSuccess) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AC_DistanceToTarget_C">();
	}
	static class UAC_DistanceToTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAC_DistanceToTarget_C>();
	}
};
static_assert(alignof(UAC_DistanceToTarget_C) == 0x000008, "Wrong alignment on UAC_DistanceToTarget_C");
static_assert(sizeof(UAC_DistanceToTarget_C) == 0x0000E0, "Wrong size on UAC_DistanceToTarget_C");
static_assert(offsetof(UAC_DistanceToTarget_C, Allow_Last_Tracked_Target) == 0x0000D8, "Member 'UAC_DistanceToTarget_C::Allow_Last_Tracked_Target' has a wrong offset!");
static_assert(offsetof(UAC_DistanceToTarget_C, bAllowEnemy) == 0x0000D9, "Member 'UAC_DistanceToTarget_C::bAllowEnemy' has a wrong offset!");
static_assert(offsetof(UAC_DistanceToTarget_C, bAllowFriendly) == 0x0000DA, "Member 'UAC_DistanceToTarget_C::bAllowFriendly' has a wrong offset!");
static_assert(offsetof(UAC_DistanceToTarget_C, bAllowNeutral) == 0x0000DB, "Member 'UAC_DistanceToTarget_C::bAllowNeutral' has a wrong offset!");

}

