#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AdvanceToEnemyPosition

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AdvanceToEnemyPosition.AdvanceToEnemyPosition_C
// 0x0010 (0x0240 - 0x0230)
class UAdvanceToEnemyPosition_C final : public UBaseCombatMoveActivity
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AReadyOrNotCharacter*                   SeekingPlayer;                                     // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AdvanceToEnemyPosition(int32 EntryPoint);
	void RequestCombatMove_Blueprint(float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AdvanceToEnemyPosition_C">();
	}
	static class UAdvanceToEnemyPosition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAdvanceToEnemyPosition_C>();
	}
};
static_assert(alignof(UAdvanceToEnemyPosition_C) == 0x000008, "Wrong alignment on UAdvanceToEnemyPosition_C");
static_assert(sizeof(UAdvanceToEnemyPosition_C) == 0x000240, "Wrong size on UAdvanceToEnemyPosition_C");
static_assert(offsetof(UAdvanceToEnemyPosition_C, UberGraphFrame) == 0x000230, "Member 'UAdvanceToEnemyPosition_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAdvanceToEnemyPosition_C, SeekingPlayer) == 0x000238, "Member 'UAdvanceToEnemyPosition_C::SeekingPlayer' has a wrong offset!");

}

