#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_DistanceToTarget

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AG_DistanceToTarget.AG_DistanceToTarget_C
// 0x0010 (0x0038 - 0x0028)
class UAG_DistanceToTarget_C final : public UAIActionGate
{
public:
	double                                        Distance;                                          // 0x0028(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAllowEnemy;                                       // 0x0030(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAllowFriendly;                                    // 0x0031(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAllowNeutral;                                     // 0x0032(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	bool CanOpen(const struct FAIActionDecisionContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AG_DistanceToTarget_C">();
	}
	static class UAG_DistanceToTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAG_DistanceToTarget_C>();
	}
};
static_assert(alignof(UAG_DistanceToTarget_C) == 0x000008, "Wrong alignment on UAG_DistanceToTarget_C");
static_assert(sizeof(UAG_DistanceToTarget_C) == 0x000038, "Wrong size on UAG_DistanceToTarget_C");
static_assert(offsetof(UAG_DistanceToTarget_C, Distance) == 0x000028, "Member 'UAG_DistanceToTarget_C::Distance' has a wrong offset!");
static_assert(offsetof(UAG_DistanceToTarget_C, bAllowEnemy) == 0x000030, "Member 'UAG_DistanceToTarget_C::bAllowEnemy' has a wrong offset!");
static_assert(offsetof(UAG_DistanceToTarget_C, bAllowFriendly) == 0x000031, "Member 'UAG_DistanceToTarget_C::bAllowFriendly' has a wrong offset!");
static_assert(offsetof(UAG_DistanceToTarget_C, bAllowNeutral) == 0x000032, "Member 'UAG_DistanceToTarget_C::bAllowNeutral' has a wrong offset!");

}

