#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_RecentlyExitedLandmark

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AG_RecentlyExitedLandmark.AG_RecentlyExitedLandmark_C
// 0x0008 (0x0030 - 0x0028)
class UAG_RecentlyExitedLandmark_C final : public UAIActionGate
{
public:
	double                                        SinceSeconds;                                      // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool CanOpen(const struct FAIActionDecisionContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AG_RecentlyExitedLandmark_C">();
	}
	static class UAG_RecentlyExitedLandmark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAG_RecentlyExitedLandmark_C>();
	}
};
static_assert(alignof(UAG_RecentlyExitedLandmark_C) == 0x000008, "Wrong alignment on UAG_RecentlyExitedLandmark_C");
static_assert(sizeof(UAG_RecentlyExitedLandmark_C) == 0x000030, "Wrong size on UAG_RecentlyExitedLandmark_C");
static_assert(offsetof(UAG_RecentlyExitedLandmark_C, SinceSeconds) == 0x000028, "Member 'UAG_RecentlyExitedLandmark_C::SinceSeconds' has a wrong offset!");

}

