#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_RecentFriendlyDeath

#include "Basic.hpp"

#include "ReadyOrNot_structs.hpp"


namespace SDK::Params
{

// Function AG_RecentFriendlyDeath.AG_RecentFriendlyDeath_C.CanOpen
// 0x0020 (0x0020 - 0x0000)
struct AG_RecentFriendlyDeath_C_CanOpen final
{
public:
	struct FAIActionDecisionContext               Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AG_RecentFriendlyDeath_C_CanOpen) == 0x000008, "Wrong alignment on AG_RecentFriendlyDeath_C_CanOpen");
static_assert(sizeof(AG_RecentFriendlyDeath_C_CanOpen) == 0x000020, "Wrong size on AG_RecentFriendlyDeath_C_CanOpen");
static_assert(offsetof(AG_RecentFriendlyDeath_C_CanOpen, Context) == 0x000000, "Member 'AG_RecentFriendlyDeath_C_CanOpen::Context' has a wrong offset!");
static_assert(offsetof(AG_RecentFriendlyDeath_C_CanOpen, ReturnValue) == 0x000010, "Member 'AG_RecentFriendlyDeath_C_CanOpen::ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_RecentFriendlyDeath_C_CanOpen, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000011, "Member 'AG_RecentFriendlyDeath_C_CanOpen::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_RecentFriendlyDeath_C_CanOpen, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x000018, "Member 'AG_RecentFriendlyDeath_C_CanOpen::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");

}

