#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_RecentFriendlyDeath

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AG_RecentFriendlyDeath.AG_RecentFriendlyDeath_C
// 0x0008 (0x0030 - 0x0028)
class UAG_RecentFriendlyDeath_C final : public UAIActionGate
{
public:
	double                                        SinceSeconds;                                      // 0x0028(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	bool CanOpen(const struct FAIActionDecisionContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AG_RecentFriendlyDeath_C">();
	}
	static class UAG_RecentFriendlyDeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAG_RecentFriendlyDeath_C>();
	}
};
static_assert(alignof(UAG_RecentFriendlyDeath_C) == 0x000008, "Wrong alignment on UAG_RecentFriendlyDeath_C");
static_assert(sizeof(UAG_RecentFriendlyDeath_C) == 0x000030, "Wrong size on UAG_RecentFriendlyDeath_C");
static_assert(offsetof(UAG_RecentFriendlyDeath_C, SinceSeconds) == 0x000028, "Member 'UAG_RecentFriendlyDeath_C::SinceSeconds' has a wrong offset!");

}

