#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_TimeSinceGameStart

#include "Basic.hpp"

#include "AdvancedSessions_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AG_TimeSinceGameStart.AG_TimeSinceGameStart_C
// 0x0010 (0x0038 - 0x0028)
class UAG_TimeSinceGameStart_C final : public UAIActionGate
{
public:
	EOnlineComparisonOpRedux                      ComparisonType;                                    // 0x0028(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Time;                                              // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool CanOpen(const struct FAIActionDecisionContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AG_TimeSinceGameStart_C">();
	}
	static class UAG_TimeSinceGameStart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAG_TimeSinceGameStart_C>();
	}
};
static_assert(alignof(UAG_TimeSinceGameStart_C) == 0x000008, "Wrong alignment on UAG_TimeSinceGameStart_C");
static_assert(sizeof(UAG_TimeSinceGameStart_C) == 0x000038, "Wrong size on UAG_TimeSinceGameStart_C");
static_assert(offsetof(UAG_TimeSinceGameStart_C, ComparisonType) == 0x000028, "Member 'UAG_TimeSinceGameStart_C::ComparisonType' has a wrong offset!");
static_assert(offsetof(UAG_TimeSinceGameStart_C, Time) == 0x000030, "Member 'UAG_TimeSinceGameStart_C::Time' has a wrong offset!");

}

