#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIAction_CheckDoors

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIAction_CheckDoors.AIAction_CheckDoors_C
// 0x0038 (0x0090 - 0x0058)
class UAIAction_CheckDoors_C final : public UAIAction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0058(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class ADoor*>                          CheckedDoors;                                      // 0x0060(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class UAnimMontage*                           CheckDoorAnimMontage;                              // 0x0070(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ADoor*                                  DoorToCheck;                                       // 0x0078(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AThreatAwarenessActor*                  NearestThreat;                                     // 0x0080(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bArrivedAtDoor;                                    // 0x0088(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bStartedMove;                                      // 0x0089(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BeginAction_Blueprint();
	void EndAction_Blueprint();
	void Event_RemoveLastCheckedDoor();
	void ExecuteUbergraph_AIAction_CheckDoors(int32 EntryPoint);
	void InitAction_Blueprint(class ACyberneticController* Controller);
	void OnCreate_Blueprint(class ACyberneticController* Controller);
	void OnMoveComplete_Blueprint(class AAIController* Controller, int32 RequestID);
	void OnPathFound_Blueprint(int32 PathId, ERonNavigationQueryResult Result);
	void ResetData();
	void Tick_Blueprint(float DeltaTime);

	void CanCheckDoor(class ADoor* Door, bool* Return_Value) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIAction_CheckDoors_C">();
	}
	static class UAIAction_CheckDoors_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIAction_CheckDoors_C>();
	}
};
static_assert(alignof(UAIAction_CheckDoors_C) == 0x000008, "Wrong alignment on UAIAction_CheckDoors_C");
static_assert(sizeof(UAIAction_CheckDoors_C) == 0x000090, "Wrong size on UAIAction_CheckDoors_C");
static_assert(offsetof(UAIAction_CheckDoors_C, UberGraphFrame) == 0x000058, "Member 'UAIAction_CheckDoors_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAIAction_CheckDoors_C, CheckedDoors) == 0x000060, "Member 'UAIAction_CheckDoors_C::CheckedDoors' has a wrong offset!");
static_assert(offsetof(UAIAction_CheckDoors_C, CheckDoorAnimMontage) == 0x000070, "Member 'UAIAction_CheckDoors_C::CheckDoorAnimMontage' has a wrong offset!");
static_assert(offsetof(UAIAction_CheckDoors_C, DoorToCheck) == 0x000078, "Member 'UAIAction_CheckDoors_C::DoorToCheck' has a wrong offset!");
static_assert(offsetof(UAIAction_CheckDoors_C, NearestThreat) == 0x000080, "Member 'UAIAction_CheckDoors_C::NearestThreat' has a wrong offset!");
static_assert(offsetof(UAIAction_CheckDoors_C, bArrivedAtDoor) == 0x000088, "Member 'UAIAction_CheckDoors_C::bArrivedAtDoor' has a wrong offset!");
static_assert(offsetof(UAIAction_CheckDoors_C, bStartedMove) == 0x000089, "Member 'UAIAction_CheckDoors_C::bStartedMove' has a wrong offset!");

}

