#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIAction_CheckDoors

#include "Basic.hpp"

#include "AIAction_CheckDoors_classes.hpp"
#include "AIAction_CheckDoors_parameters.hpp"


namespace SDK
{

// Function AIAction_CheckDoors.AIAction_CheckDoors_C.BeginAction_Blueprint
// (Event, Protected, BlueprintEvent)

void UAIAction_CheckDoors_C::BeginAction_Blueprint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "BeginAction_Blueprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.EndAction_Blueprint
// (Event, Protected, BlueprintEvent)

void UAIAction_CheckDoors_C::EndAction_Blueprint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "EndAction_Blueprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.Event_RemoveLastCheckedDoor
// (BlueprintCallable, BlueprintEvent)

void UAIAction_CheckDoors_C::Event_RemoveLastCheckedDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "Event_RemoveLastCheckedDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.ExecuteUbergraph_AIAction_CheckDoors
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::ExecuteUbergraph_AIAction_CheckDoors(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "ExecuteUbergraph_AIAction_CheckDoors");

	Params::AIAction_CheckDoors_C_ExecuteUbergraph_AIAction_CheckDoors Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.InitAction_Blueprint
// (Event, Protected, BlueprintEvent)
// Parameters:
// class ACyberneticController*            Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::InitAction_Blueprint(class ACyberneticController* Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "InitAction_Blueprint");

	Params::AIAction_CheckDoors_C_InitAction_Blueprint Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.OnCreate_Blueprint
// (Event, Protected, BlueprintEvent)
// Parameters:
// class ACyberneticController*            Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::OnCreate_Blueprint(class ACyberneticController* Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "OnCreate_Blueprint");

	Params::AIAction_CheckDoors_C_OnCreate_Blueprint Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.OnMoveComplete_Blueprint
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   RequestID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::OnMoveComplete_Blueprint(class AAIController* Controller, int32 RequestID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "OnMoveComplete_Blueprint");

	Params::AIAction_CheckDoors_C_OnMoveComplete_Blueprint Parms{};

	Parms.Controller = Controller;
	Parms.RequestID = RequestID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.OnPathFound_Blueprint
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   PathId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ERonNavigationQueryResult               Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::OnPathFound_Blueprint(int32 PathId, ERonNavigationQueryResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "OnPathFound_Blueprint");

	Params::AIAction_CheckDoors_C_OnPathFound_Blueprint Parms{};

	Parms.PathId = PathId;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.ResetData
// (Public, BlueprintCallable, BlueprintEvent)

void UAIAction_CheckDoors_C::ResetData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "ResetData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.Tick_Blueprint
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::Tick_Blueprint(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "Tick_Blueprint");

	Params::AIAction_CheckDoors_C_Tick_Blueprint Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_CheckDoors.AIAction_CheckDoors_C.CanCheckDoor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ADoor*                            Door                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Return_Value                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAIAction_CheckDoors_C::CanCheckDoor(class ADoor* Door, bool* Return_Value) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_CheckDoors_C", "CanCheckDoor");

	Params::AIAction_CheckDoors_C_CanCheckDoor Parms{};

	Parms.Door = Door;

	UObject::ProcessEvent(Func, &Parms);

	if (Return_Value != nullptr)
		*Return_Value = Parms.Return_Value;
}

}

