#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIAction_FireRandomly

#include "Basic.hpp"

#include "AIAction_FireRandomly_classes.hpp"
#include "AIAction_FireRandomly_parameters.hpp"


namespace SDK
{

// Function AIAction_FireRandomly.AIAction_FireRandomly_C.BeginAction_Blueprint
// (Event, Protected, BlueprintEvent)

void UAIAction_FireRandomly_C::BeginAction_Blueprint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_FireRandomly_C", "BeginAction_Blueprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIAction_FireRandomly.AIAction_FireRandomly_C.EndAction_Blueprint
// (Event, Protected, BlueprintEvent)

void UAIAction_FireRandomly_C::EndAction_Blueprint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_FireRandomly_C", "EndAction_Blueprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AIAction_FireRandomly.AIAction_FireRandomly_C.ExecuteUbergraph_AIAction_FireRandomly
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAIAction_FireRandomly_C::ExecuteUbergraph_AIAction_FireRandomly(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_FireRandomly_C", "ExecuteUbergraph_AIAction_FireRandomly");

	Params::AIAction_FireRandomly_C_ExecuteUbergraph_AIAction_FireRandomly Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AIAction_FireRandomly.AIAction_FireRandomly_C.ShouldPerformAction
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UAIAction_FireRandomly_C::ShouldPerformAction() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AIAction_FireRandomly_C", "ShouldPerformAction");

	Params::AIAction_FireRandomly_C_ShouldPerformAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

