#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANIMBP_CAR

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ANIMBP_CAR.ANIMBP_CAR_C
// 0x01F0 (0x0560 - 0x0370)
class UANIMBP_CAR_C final : public URoNWeaponAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0378(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0380(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0388(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x03A8(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x04D0(0x0020)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x04F0(0x0048)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0538(0x0020)()
	double                                        MagScale;                                          // 0x0558(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_EjectMag();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_ANIMBP_CAR(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ANIMBP_CAR_C">();
	}
	static class UANIMBP_CAR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UANIMBP_CAR_C>();
	}
};
static_assert(alignof(UANIMBP_CAR_C) == 0x000010, "Wrong alignment on UANIMBP_CAR_C");
static_assert(sizeof(UANIMBP_CAR_C) == 0x000560, "Wrong size on UANIMBP_CAR_C");
static_assert(offsetof(UANIMBP_CAR_C, UberGraphFrame) == 0x000370, "Member 'UANIMBP_CAR_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimBlueprintExtension_PropertyAccess) == 0x000378, "Member 'UANIMBP_CAR_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimBlueprintExtension_Base) == 0x000380, "Member 'UANIMBP_CAR_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimGraphNode_Root) == 0x000388, "Member 'UANIMBP_CAR_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimGraphNode_ModifyBone) == 0x0003A8, "Member 'UANIMBP_CAR_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimGraphNode_ComponentToLocalSpace) == 0x0004D0, "Member 'UANIMBP_CAR_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimGraphNode_Slot) == 0x0004F0, "Member 'UANIMBP_CAR_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, AnimGraphNode_LocalToComponentSpace) == 0x000538, "Member 'UANIMBP_CAR_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UANIMBP_CAR_C, MagScale) == 0x000558, "Member 'UANIMBP_CAR_C::MagScale' has a wrong offset!");

}

