#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANIMBP_TAC700

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ANIMBP_TAC700_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ANIMBP_TAC700.ANIMBP_TAC700_C
// 0x0370 (0x06E0 - 0x0370)
class UANIMBP_TAC700_C final : public URoNWeaponAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct ANIMBP_TAC700::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                // 0x0378(0x0002)(HasGetValueTypeHash)
	uint8                                         Pad_37A[0x6];                                      // 0x037A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0380(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0388(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0390(0x0020)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x03B0(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x03F8(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0440(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0488(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x04D0(0x0080)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0550(0x00F0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0640(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x0688(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x06B0(0x0028)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ANIMBP_TAC700_AnimGraphNode_BlendListByBool_891F13364F4DC947D429C99B1543CDB7();
	void ExecuteUbergraph_ANIMBP_TAC700(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ANIMBP_TAC700_C">();
	}
	static class UANIMBP_TAC700_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UANIMBP_TAC700_C>();
	}
};
static_assert(alignof(UANIMBP_TAC700_C) == 0x000010, "Wrong alignment on UANIMBP_TAC700_C");
static_assert(sizeof(UANIMBP_TAC700_C) == 0x0006E0, "Wrong size on UANIMBP_TAC700_C");
static_assert(offsetof(UANIMBP_TAC700_C, UberGraphFrame) == 0x000370, "Member 'UANIMBP_TAC700_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, __AnimBlueprintMutables) == 0x000378, "Member 'UANIMBP_TAC700_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimBlueprintExtension_PropertyAccess) == 0x000380, "Member 'UANIMBP_TAC700_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimBlueprintExtension_Base) == 0x000388, "Member 'UANIMBP_TAC700_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_Root) == 0x000390, "Member 'UANIMBP_TAC700_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_Slot_1) == 0x0003B0, "Member 'UANIMBP_TAC700_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_BlendListByBool) == 0x0003F8, "Member 'UANIMBP_TAC700_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_SequencePlayer_1) == 0x000440, "Member 'UANIMBP_TAC700_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_SequencePlayer) == 0x000488, "Member 'UANIMBP_TAC700_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_SaveCachedPose) == 0x0004D0, "Member 'UANIMBP_TAC700_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_LayeredBoneBlend) == 0x000550, "Member 'UANIMBP_TAC700_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_Slot) == 0x000640, "Member 'UANIMBP_TAC700_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_UseCachedPose_1) == 0x000688, "Member 'UANIMBP_TAC700_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UANIMBP_TAC700_C, AnimGraphNode_UseCachedPose) == 0x0006B0, "Member 'UANIMBP_TAC700_C::AnimGraphNode_UseCachedPose' has a wrong offset!");

}

