#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANIMBP_TelescopicLadder

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct ANIMBP_TelescopicLadder.ANIMBP_TelescopicLadder_C.AnimBlueprintGeneratedConstantData
// 0x0107 (0x0108 - 0x0001)
struct ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	bool                                          __BoolProperty_23;                                 // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_24;                                // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_25;                                // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_26;                                // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_27;                                 // 0x0010(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_28;                                 // 0x0011(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlendProfile*                          __BlendProfile_29;                                 // 0x0018(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_30;                                   // 0x0020(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_31;                                 // 0x0028(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_32;                                 // 0x0029(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_33;                                 // 0x002A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B[0x5];                                       // 0x002B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_34;                                // 0x0030(0x0010)(BlueprintVisible, EditFixedSize)
	struct FAnimNodeFunctionRef                   __StructProperty_35;                               // 0x0040(0x0020)(BlueprintVisible, NoDestructor)
	class FName                                   __NameProperty_36;                                 // 0x0060(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_37;                                 // 0x0068(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0070(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x00F0(0x0018)()
};
static_assert(alignof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData) == 0x000108, "Wrong size on ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __BoolProperty_23) == 0x000001, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__BoolProperty_23' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __FloatProperty_24) == 0x000004, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__FloatProperty_24' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __FloatProperty_25) == 0x000008, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__FloatProperty_25' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __FloatProperty_26) == 0x00000C, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__FloatProperty_26' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __EnumProperty_27) == 0x000010, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__EnumProperty_27' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __ByteProperty_28) == 0x000011, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__ByteProperty_28' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __BlendProfile_29) == 0x000018, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__BlendProfile_29' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __CurveFloat_30) == 0x000020, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__CurveFloat_30' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __BoolProperty_31) == 0x000028, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__BoolProperty_31' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __EnumProperty_32) == 0x000029, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__EnumProperty_32' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __EnumProperty_33) == 0x00002A, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__EnumProperty_33' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __ArrayProperty_34) == 0x000030, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__ArrayProperty_34' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __StructProperty_35) == 0x000040, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__StructProperty_35' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __NameProperty_36) == 0x000060, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__NameProperty_36' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, __NameProperty_37) == 0x000068, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::__NameProperty_37' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000070, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x0000F0, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct ANIMBP_TelescopicLadder.ANIMBP_TelescopicLadder_C.AnimBlueprintGeneratedMutableData
// 0x000B (0x000C - 0x0001)
struct ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty;                                   // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData) == 0x000004, "Wrong alignment on ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData) == 0x00000C, "Wrong size on ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData, __FloatProperty) == 0x000004, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData::__FloatProperty' has a wrong offset!");
static_assert(offsetof(ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000008, "Member 'ANIMBP_TelescopicLadder::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");

}

