#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LensFlare_MAWL

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LensFlare_MAWL.BP_LensFlare_MAWL_C
// 0x0000 (0x0578 - 0x0578)
class ABP_LensFlare_MAWL_C final : public ALensFlare
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LensFlare_MAWL_C">();
	}
	static class ABP_LensFlare_MAWL_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LensFlare_MAWL_C>();
	}
};
static_assert(alignof(ABP_LensFlare_MAWL_C) == 0x000008, "Wrong alignment on ABP_LensFlare_MAWL_C");
static_assert(sizeof(ABP_LensFlare_MAWL_C) == 0x000578, "Wrong size on ABP_LensFlare_MAWL_C");

}

