#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_TabSetting

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "BPS_SMM_PageInfo_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_TabSetting.BPW_SMM_TabSetting_C
// 0x0860 (0x0B20 - 0x02C0)
class UBPW_SMM_TabSetting_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_ActiveFlair;                                // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_KeyboardFocus;                              // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Tab;                                        // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_Title;                                // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TabDisplayName;                                    // 0x02E8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FName                                   TabKey;                                            // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<struct FBPS_SMM_PageInfo>              Pages;                                             // 0x0308(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	TMulticastInlineDelegate<void(class UBPW_SMM_TabSetting_C* SettingTabWidget, bool Keyboard)> SettingTabSelected; // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         SortOrder;                                         // 0x0328(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          TabState;                                          // 0x032C(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          NewVar;                                            // 0x032D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32E[0x2];                                      // 0x032E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           StyleFalse;                                        // 0x0330(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FButtonStyle                           StyleTrue;                                         // 0x0720(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UBPW_SMM_Settings_Pages_Container_C*    Container;                                         // 0x0B10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_TabSetting_Button_Tab_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void CreateContainer(class UWidgetSwitcher* WidgetSwitcher, TScriptInterface<class IBPI_SMM_UI_C> SMM_UI);
	class UWidget* DoCustomNavigation(EUINavigation Navigation_0);
	void ExecuteUbergraph_BPW_SMM_TabSetting(int32 EntryPoint);
	void HideFocus();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRep_TabState();
	void PreConstruct(bool IsDesignTime);
	void UpdateTabVisuals(bool Selected);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_SMM_TabSetting_C">();
	}
	static class UBPW_SMM_TabSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_TabSetting_C>();
	}
};
static_assert(alignof(UBPW_SMM_TabSetting_C) == 0x000010, "Wrong alignment on UBPW_SMM_TabSetting_C");
static_assert(sizeof(UBPW_SMM_TabSetting_C) == 0x000B20, "Wrong size on UBPW_SMM_TabSetting_C");
static_assert(offsetof(UBPW_SMM_TabSetting_C, UberGraphFrame) == 0x0002C0, "Member 'UBPW_SMM_TabSetting_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, Border_ActiveFlair) == 0x0002C8, "Member 'UBPW_SMM_TabSetting_C::Border_ActiveFlair' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, Border_KeyboardFocus) == 0x0002D0, "Member 'UBPW_SMM_TabSetting_C::Border_KeyboardFocus' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, Button_Tab) == 0x0002D8, "Member 'UBPW_SMM_TabSetting_C::Button_Tab' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, EditableText_Title) == 0x0002E0, "Member 'UBPW_SMM_TabSetting_C::EditableText_Title' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, TabDisplayName) == 0x0002E8, "Member 'UBPW_SMM_TabSetting_C::TabDisplayName' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, TabKey) == 0x000300, "Member 'UBPW_SMM_TabSetting_C::TabKey' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, Pages) == 0x000308, "Member 'UBPW_SMM_TabSetting_C::Pages' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, SettingTabSelected) == 0x000318, "Member 'UBPW_SMM_TabSetting_C::SettingTabSelected' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, SortOrder) == 0x000328, "Member 'UBPW_SMM_TabSetting_C::SortOrder' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, TabState) == 0x00032C, "Member 'UBPW_SMM_TabSetting_C::TabState' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, NewVar) == 0x00032D, "Member 'UBPW_SMM_TabSetting_C::NewVar' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, StyleFalse) == 0x000330, "Member 'UBPW_SMM_TabSetting_C::StyleFalse' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, StyleTrue) == 0x000720, "Member 'UBPW_SMM_TabSetting_C::StyleTrue' has a wrong offset!");
static_assert(offsetof(UBPW_SMM_TabSetting_C, Container) == 0x000B10, "Member 'UBPW_SMM_TabSetting_C::Container' has a wrong offset!");

}

