#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraSaveGame

#include "Basic.hpp"

#include "CameraSaveGame_classes.hpp"
#include "CameraSaveGame_parameters.hpp"


namespace SDK
{

// Function CameraSaveGame.CameraSaveGame_C.ExecuteUbergraph_CameraSaveGame
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCameraSaveGame_C::ExecuteUbergraph_CameraSaveGame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraSaveGame_C", "ExecuteUbergraph_CameraSaveGame");

	Params::CameraSaveGame_C_ExecuteUbergraph_CameraSaveGame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CameraSaveGame.CameraSaveGame_C.Get
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_Main_C*                        W_Main                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UCameraSaveGame_C::Get(class UW_Main_C* W_Main)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraSaveGame_C", "Get");

	Params::CameraSaveGame_C_Get Parms{};

	Parms.W_Main = W_Main;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CameraSaveGame.CameraSaveGame_C.Set
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_Main_C*                        W_Main                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UCameraSaveGame_C::Set(class UW_Main_C* W_Main)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraSaveGame_C", "Set");

	Params::CameraSaveGame_C_Set Parms{};

	Parms.W_Main = W_Main;

	UObject::ProcessEvent(Func, &Parms);
}

}

