#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cybernetics_Civilian_V2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cybernetics_Civilian_V2.Cybernetics_Civilian_V2_C
// 0x0010 (0x2560 - 0x2550)
class ACybernetics_Civilian_V2_C final : public ACivilianCharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2550(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   In_Bone_Name;                                      // 0x2558(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Cybernetics_Civilian_V2(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cybernetics_Civilian_V2_C">();
	}
	static class ACybernetics_Civilian_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACybernetics_Civilian_V2_C>();
	}
};
static_assert(alignof(ACybernetics_Civilian_V2_C) == 0x000010, "Wrong alignment on ACybernetics_Civilian_V2_C");
static_assert(sizeof(ACybernetics_Civilian_V2_C) == 0x002560, "Wrong size on ACybernetics_Civilian_V2_C");
static_assert(offsetof(ACybernetics_Civilian_V2_C, UberGraphFrame) == 0x002550, "Member 'ACybernetics_Civilian_V2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ACybernetics_Civilian_V2_C, In_Bone_Name) == 0x002558, "Member 'ACybernetics_Civilian_V2_C::In_Bone_Name' has a wrong offset!");

}

