#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KeybindSaveGame

#include "Basic.hpp"

#include "AxisMapArrayStruct_structs.hpp"
#include "ActionMapArrayStruct_structs.hpp"


namespace SDK::Params
{

// Function KeybindSaveGame.KeybindSaveGame_C.ExecuteUbergraph_KeybindSaveGame
// 0x0228 (0x0228 - 0x0000)
struct KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAxisMapArrayStruct                    CallFunc_Array_Get_Item;                           // 0x0028(0x0050)(HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_85[0x3];                                       // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Main_C*                              K2Node_CustomEvent_W_Main_1;                       // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x00A0(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWidget*                                CallFunc_Array_Get_Item_1;                         // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_KeybindAxisMap_C*                    K2Node_DynamicCast_AsW_Keybind_Axis_Map;           // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA[0x6];                                       // 0x00CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_KeybindActionMap_C*                  K2Node_DynamicCast_AsW_Keybind_Action_Map;         // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAxisMapArrayStruct                    K2Node_MakeStruct_AxisMapArrayStruct;              // 0x00E0(0x0050)(HasGetValueTypeHash)
	struct FActionMapArrayStruct                  K2Node_MakeStruct_ActionMapArrayStruct;            // 0x0130(0x0048)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Main_C*                              K2Node_CustomEvent_W_Main;                         // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FActionMapArrayStruct                  CallFunc_Array_Get_Item_2;                         // 0x0188(0x0048)(HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue_1;             // 0x01D0(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWidget*                                CallFunc_Array_Get_Item_3;                         // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_KeybindAxisMap_C*                    K2Node_DynamicCast_AsW_Keybind_Axis_Map_1;         // 0x01F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x01FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x01FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FC[0x4];                                      // 0x01FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_KeybindActionMap_C*                  K2Node_DynamicCast_AsW_Keybind_Action_Map_1;       // 0x0200(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0209(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue_1;        // 0x020A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20B[0x1];                                      // 0x020B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x020C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0211(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_212[0x6];                                      // 0x0212(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Scale_21_9AF2E94846B48FD35910DB93C0AC3866_ImplicitCast; // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame) == 0x000008, "Wrong alignment on KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame");
static_assert(sizeof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame) == 0x000228, "Wrong size on KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, EntryPoint) == 0x000000, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::EntryPoint' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Length_ReturnValue) == 0x000008, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Loop_Counter_Variable_1) == 0x000010, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Less_IntInt_ReturnValue) == 0x000014, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Add_IntInt_ReturnValue_1) == 0x000018, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Loop_Counter_Variable_2) == 0x000020, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Get_Item) == 0x000028, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Add_IntInt_ReturnValue_2) == 0x000078, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Loop_Counter_Variable_3) == 0x00007C, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Add_IntInt_ReturnValue_3) == 0x000080, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_bool_True_if_break_was_hit_Variable) == 0x000084, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Array_Index_Variable_1) == 0x000088, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Not_PreBool_ReturnValue) == 0x00008C, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Array_Index_Variable_2) == 0x000090, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, Temp_int_Array_Index_Variable_3) == 0x000094, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_CustomEvent_W_Main_1) == 0x000098, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_CustomEvent_W_Main_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_GetAllChildren_ReturnValue) == 0x0000A0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Get_Item_1) == 0x0000B0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Length_ReturnValue_1) == 0x0000B8, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_AsW_Keybind_Axis_Map) == 0x0000C0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_AsW_Keybind_Axis_Map' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_bSuccess) == 0x0000C8, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000C9, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_AsW_Keybind_Action_Map) == 0x0000D0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_AsW_Keybind_Action_Map' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_bSuccess_1) == 0x0000D8, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_MakeStruct_AxisMapArrayStruct) == 0x0000E0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_MakeStruct_AxisMapArrayStruct' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_MakeStruct_ActionMapArrayStruct) == 0x000130, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_MakeStruct_ActionMapArrayStruct' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Add_ReturnValue) == 0x000178, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Add_ReturnValue_1) == 0x00017C, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_CustomEvent_W_Main) == 0x000180, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_CustomEvent_W_Main' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Get_Item_2) == 0x000188, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_GetAllChildren_ReturnValue_1) == 0x0001D0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_GetAllChildren_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Get_Item_3) == 0x0001E0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Length_ReturnValue_2) == 0x0001E8, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_AsW_Keybind_Axis_Map_1) == 0x0001F0, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_AsW_Keybind_Axis_Map_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_bSuccess_2) == 0x0001F8, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Less_IntInt_ReturnValue_2) == 0x0001F9, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_EqualEqual_DoubleDouble_ReturnValue) == 0x0001FA, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_EqualEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_EqualEqual_NameName_ReturnValue) == 0x0001FB, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_AsW_Keybind_Action_Map_1) == 0x000200, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_AsW_Keybind_Action_Map_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_DynamicCast_bSuccess_3) == 0x000208, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_BooleanAND_ReturnValue) == 0x000209, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_EqualEqual_NameName_ReturnValue_1) == 0x00020A, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_EqualEqual_NameName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Array_Length_ReturnValue_3) == 0x00020C, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_Less_IntInt_ReturnValue_3) == 0x000210, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_BooleanAND_ReturnValue_1) == 0x000211, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast) == 0x000218, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame, K2Node_MakeStruct_Scale_21_9AF2E94846B48FD35910DB93C0AC3866_ImplicitCast) == 0x000220, "Member 'KeybindSaveGame_C_ExecuteUbergraph_KeybindSaveGame::K2Node_MakeStruct_Scale_21_9AF2E94846B48FD35910DB93C0AC3866_ImplicitCast' has a wrong offset!");

// Function KeybindSaveGame.KeybindSaveGame_C.Get
// 0x0008 (0x0008 - 0x0000)
struct KeybindSaveGame_C_Get final
{
public:
	class UW_Main_C*                              W_Main;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(KeybindSaveGame_C_Get) == 0x000008, "Wrong alignment on KeybindSaveGame_C_Get");
static_assert(sizeof(KeybindSaveGame_C_Get) == 0x000008, "Wrong size on KeybindSaveGame_C_Get");
static_assert(offsetof(KeybindSaveGame_C_Get, W_Main) == 0x000000, "Member 'KeybindSaveGame_C_Get::W_Main' has a wrong offset!");

// Function KeybindSaveGame.KeybindSaveGame_C.Set
// 0x0008 (0x0008 - 0x0000)
struct KeybindSaveGame_C_Set final
{
public:
	class UW_Main_C*                              W_Main;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(KeybindSaveGame_C_Set) == 0x000008, "Wrong alignment on KeybindSaveGame_C_Set");
static_assert(sizeof(KeybindSaveGame_C_Set) == 0x000008, "Wrong size on KeybindSaveGame_C_Set");
static_assert(offsetof(KeybindSaveGame_C_Set, W_Main) == 0x000000, "Member 'KeybindSaveGame_C_Set::W_Main' has a wrong offset!");

}

