#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LauncherProjectile_Gas_V2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LauncherProjectile_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LauncherProjectile_Gas_V2.LauncherProjectile_Gas_V2_C
// 0x0010 (0x04F0 - 0x04E0)
class ALauncherProjectile_Gas_V2_C final : public ALauncherProjectile_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          FiredOffEffect;                                    // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsActive;                                          // 0x04E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LauncherProjectile_Gas_V2(int32 EntryPoint);
	void OnDetonate_Blueprint();
	void OnDetonationComplete_Blueprint();

	bool AffectsNavigation() const;
	bool AppliesStunDamage() const;
	float GetGasRadius() const;
	bool GetGasReleaseLocation(struct FVector* OutLocation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LauncherProjectile_Gas_V2_C">();
	}
	static class ALauncherProjectile_Gas_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALauncherProjectile_Gas_V2_C>();
	}
};
static_assert(alignof(ALauncherProjectile_Gas_V2_C) == 0x000008, "Wrong alignment on ALauncherProjectile_Gas_V2_C");
static_assert(sizeof(ALauncherProjectile_Gas_V2_C) == 0x0004F0, "Wrong size on ALauncherProjectile_Gas_V2_C");
static_assert(offsetof(ALauncherProjectile_Gas_V2_C, UberGraphFrame) == 0x0004E0, "Member 'ALauncherProjectile_Gas_V2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ALauncherProjectile_Gas_V2_C, FiredOffEffect) == 0x0004E8, "Member 'ALauncherProjectile_Gas_V2_C::FiredOffEffect' has a wrong offset!");
static_assert(offsetof(ALauncherProjectile_Gas_V2_C, IsActive) == 0x0004E9, "Member 'ALauncherProjectile_Gas_V2_C::IsActive' has a wrong offset!");

}

