#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PointSaveGame

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PointSaveGame.PointSaveGame_C
// 0x0048 (0x0070 - 0x0028)
class UPointSaveGame_C final : public USaveGame
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FString                                 PointSaveName;                                     // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class FString>                         PointNames;                                        // 0x0040(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FVector>                        PointLocations;                                    // 0x0050(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FRotator>                       PointRotations;                                    // 0x0060(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_PointSaveGame(int32 EntryPoint);
	void Get(class UW_Main_C* W_Main);
	void Set(class UW_Main_C* W_Main);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PointSaveGame_C">();
	}
	static class UPointSaveGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPointSaveGame_C>();
	}
};
static_assert(alignof(UPointSaveGame_C) == 0x000008, "Wrong alignment on UPointSaveGame_C");
static_assert(sizeof(UPointSaveGame_C) == 0x000070, "Wrong size on UPointSaveGame_C");
static_assert(offsetof(UPointSaveGame_C, UberGraphFrame) == 0x000028, "Member 'UPointSaveGame_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPointSaveGame_C, PointSaveName) == 0x000030, "Member 'UPointSaveGame_C::PointSaveName' has a wrong offset!");
static_assert(offsetof(UPointSaveGame_C, PointNames) == 0x000040, "Member 'UPointSaveGame_C::PointNames' has a wrong offset!");
static_assert(offsetof(UPointSaveGame_C, PointLocations) == 0x000050, "Member 'UPointSaveGame_C::PointLocations' has a wrong offset!");
static_assert(offsetof(UPointSaveGame_C, PointRotations) == 0x000060, "Member 'UPointSaveGame_C::PointRotations' has a wrong offset!");

}

