#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Primary_MP5A2

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Primary_MP5A2.Primary_MP5A2_C
// 0x0000 (0x1740 - 0x1740)
class APrimary_MP5A2_C final : public ABaseMagazineWeapon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Primary_MP5A2_C">();
	}
	static class APrimary_MP5A2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrimary_MP5A2_C>();
	}
};
static_assert(alignof(APrimary_MP5A2_C) == 0x000010, "Wrong alignment on APrimary_MP5A2_C");
static_assert(sizeof(APrimary_MP5A2_C) == 0x001740, "Wrong size on APrimary_MP5A2_C");

}

