#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_Flare

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Projectile_Flare.Projectile_Flare_C.ExecuteUbergraph_Projectile_Flare
// 0x0160 (0x0160 - 0x0000)
struct Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0xC];                                        // 0x0004(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0010(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0070(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0088(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x00A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0xF];                                       // 0x00D1(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x00E0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_LensFlare_FlareGun_C*               CallFunc_FinishSpawningActor_ReturnValue;          // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_151[0x3];                                      // 0x0151(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare) == 0x000010, "Wrong alignment on Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare");
static_assert(sizeof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare) == 0x000160, "Wrong size on Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, EntryPoint) == 0x000000, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::EntryPoint' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_GetTransform_ReturnValue) == 0x000010, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_BreakTransform_Location) == 0x000070, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_BreakTransform_Rotation) == 0x000088, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_BreakTransform_Scale) == 0x0000A0, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_Add_VectorVector_ReturnValue) == 0x0000B8, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_IsValid_ReturnValue) == 0x0000D0, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_MakeTransform_ReturnValue) == 0x0000E0, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000140, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_FinishSpawningActor_ReturnValue) == 0x000148, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000150, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare, CallFunc_SetScalarParameterValue_Value_ImplicitCast) == 0x000154, "Member 'Projectile_Flare_C_ExecuteUbergraph_Projectile_Flare::CallFunc_SetScalarParameterValue_Value_ImplicitCast' has a wrong offset!");

}

