#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RedButtonStyle

#include "Basic.hpp"

#include "DefaultButtonStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RedButtonStyle.RedButtonStyle_C
// 0x0000 (0x07E0 - 0x07E0)
class URedButtonStyle_C final : public UDefaultButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RedButtonStyle_C">();
	}
	static class URedButtonStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URedButtonStyle_C>();
	}
};
static_assert(alignof(URedButtonStyle_C) == 0x000010, "Wrong alignment on URedButtonStyle_C");
static_assert(sizeof(URedButtonStyle_C) == 0x0007E0, "Wrong size on URedButtonStyle_C");

}

