#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_AttachmentItem

#include "Basic.hpp"

#include "W_AttachmentItem_classes.hpp"
#include "W_AttachmentItem_parameters.hpp"


namespace SDK
{

// Function W_AttachmentItem.W_AttachmentItem_C.BndEvt__Button_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature
// (BlueprintEvent)

void UW_AttachmentItem_C::BndEvt__Button_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "BndEvt__Button_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.BndEvt__Button_K2Node_ComponentBoundEvent_1_OnReleased__DelegateSignature
// (BlueprintEvent)

void UW_AttachmentItem_C::BndEvt__Button_K2Node_ComponentBoundEvent_1_OnReleased__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "BndEvt__Button_K2Node_ComponentBoundEvent_1_OnReleased__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_StandardButton_C*              CallingButton                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_AttachmentItem_C::BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature(class UW_StandardButton_C* CallingButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	Params::W_AttachmentItem_C_BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature Parms{};

	Parms.CallingButton = CallingButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_AttachmentItem.W_AttachmentItem_C.BndEvt__Button_K2Node_ComponentBoundEvent_4_OnHovered__DelegateSignature
// (BlueprintEvent)

void UW_AttachmentItem_C::BndEvt__Button_K2Node_ComponentBoundEvent_4_OnHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "BndEvt__Button_K2Node_ComponentBoundEvent_4_OnHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.BndEvt__Button_K2Node_ComponentBoundEvent_5_OnUnhovered__DelegateSignature
// (BlueprintEvent)

void UW_AttachmentItem_C::BndEvt__Button_K2Node_ComponentBoundEvent_5_OnUnhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "BndEvt__Button_K2Node_ComponentBoundEvent_5_OnUnhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.Deselect
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::Deselect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "Deselect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.ExecuteUbergraph_W_AttachmentItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_AttachmentItem_C::ExecuteUbergraph_W_AttachmentItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "ExecuteUbergraph_W_AttachmentItem");

	Params::W_AttachmentItem_C_ExecuteUbergraph_W_AttachmentItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_AttachmentItem.W_AttachmentItem_C.Get_ItemClassName_Text_Visibility
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UW_AttachmentItem_C::Get_ItemClassName_Text_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "Get_ItemClassName_Text_Visibility");

	Params::W_AttachmentItem_C_Get_ItemClassName_Text_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_AttachmentItem.W_AttachmentItem_C.HighlightBorder
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::HighlightBorder()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "HighlightBorder");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.OnGunCleaned
// (BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::OnGunCleaned()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "OnGunCleaned");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.OnLoadoutLoaded
// (BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::OnLoadoutLoaded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "OnLoadoutLoaded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_AttachmentItem_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "PreConstruct");

	Params::W_AttachmentItem_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_AttachmentItem.W_AttachmentItem_C.Select
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::Select()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "Select");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.SimulateClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::SimulateClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "SimulateClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.SimulateHover
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::SimulateHover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "SimulateHover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.SimulateUnhover
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::SimulateUnhover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "SimulateUnhover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.UnhighlightBorder
// (Public, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::UnhighlightBorder()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "UnhighlightBorder");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_AttachmentItem.W_AttachmentItem_C.UpdateAttachmentName
// (Private, BlueprintCallable, BlueprintEvent)

void UW_AttachmentItem_C::UpdateAttachmentName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_AttachmentItem_C", "UpdateAttachmentName");

	UObject::ProcessEvent(Func, nullptr);
}

}

