#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Briefing_Dossier_Rapsheet

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "ReadyOrNot_structs.hpp"
#include "Engine_structs.hpp"
#include "ST_Character_RapSheet_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Briefing_Dossier_Rapsheet.W_Briefing_Dossier_Rapsheet_C
// 0x0058 (0x0318 - 0x02C0)
class UW_Briefing_Dossier_Rapsheet_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_23;                                          // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              lbl_Code;                                          // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Text_C*                              lbl_Rapsheet;                                      // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_RapsheetEntries;                                // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<struct FCriminalRecord>                RapSheet;                                          // 0x02E8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FST_Character_RapSheet                 DebugRapsheet;                                     // 0x02F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<struct FCriminalRecord>                CriminalRecord;                                    // 0x0308(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_W_Briefing_Dossier_Rapsheet(int32 EntryPoint);
	void Initialize(const TArray<struct FCriminalRecord>& CriminalRecord_0);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Briefing_Dossier_Rapsheet_C">();
	}
	static class UW_Briefing_Dossier_Rapsheet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Briefing_Dossier_Rapsheet_C>();
	}
};
static_assert(alignof(UW_Briefing_Dossier_Rapsheet_C) == 0x000008, "Wrong alignment on UW_Briefing_Dossier_Rapsheet_C");
static_assert(sizeof(UW_Briefing_Dossier_Rapsheet_C) == 0x000318, "Wrong size on UW_Briefing_Dossier_Rapsheet_C");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, UberGraphFrame) == 0x0002C0, "Member 'UW_Briefing_Dossier_Rapsheet_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, Image_23) == 0x0002C8, "Member 'UW_Briefing_Dossier_Rapsheet_C::Image_23' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, lbl_Code) == 0x0002D0, "Member 'UW_Briefing_Dossier_Rapsheet_C::lbl_Code' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, lbl_Rapsheet) == 0x0002D8, "Member 'UW_Briefing_Dossier_Rapsheet_C::lbl_Rapsheet' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, VB_RapsheetEntries) == 0x0002E0, "Member 'UW_Briefing_Dossier_Rapsheet_C::VB_RapsheetEntries' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, RapSheet) == 0x0002E8, "Member 'UW_Briefing_Dossier_Rapsheet_C::RapSheet' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, DebugRapsheet) == 0x0002F8, "Member 'UW_Briefing_Dossier_Rapsheet_C::DebugRapsheet' has a wrong offset!");
static_assert(offsetof(UW_Briefing_Dossier_Rapsheet_C, CriminalRecord) == 0x000308, "Member 'UW_Briefing_Dossier_Rapsheet_C::CriminalRecord' has a wrong offset!");

}

