#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CommanderProfileSelect

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature final
{
public:
	class UW_Button_C*                            Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");
static_assert(sizeof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");
static_assert(offsetof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature, Button) == 0x000000, "Member 'W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_Example_BackButton_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature::Button' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature final
{
public:
	class FString                                 ButtonID;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature");
static_assert(sizeof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature) == 0x000010, "Wrong size on W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature");
static_assert(offsetof(W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature, ButtonID) == 0x000000, "Member 'W_CommanderProfileSelect_C_BndEvt__W_CommanderProfileSelect_PageWrapper_K2Node_ComponentBoundEvent_2_OnFooterButtonClicked__DelegateSignature::ButtonID' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.CancelDelete
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_CancelDelete final
{
public:
	class UStandardModal*                         CallingModal;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_CancelDelete) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_CancelDelete");
static_assert(sizeof(W_CommanderProfileSelect_C_CancelDelete) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_CancelDelete");
static_assert(offsetof(W_CommanderProfileSelect_C_CancelDelete, CallingModal) == 0x000000, "Member 'W_CommanderProfileSelect_C_CancelDelete::CallingModal' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.DeleteSave
// 0x0020 (0x0020 - 0x0000)
struct W_CommanderProfileSelect_C_DeleteSave final
{
public:
	class UW_StandardModal_C*                     CallingModal;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   TextEntry;                                         // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(W_CommanderProfileSelect_C_DeleteSave) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_DeleteSave");
static_assert(sizeof(W_CommanderProfileSelect_C_DeleteSave) == 0x000020, "Wrong size on W_CommanderProfileSelect_C_DeleteSave");
static_assert(offsetof(W_CommanderProfileSelect_C_DeleteSave, CallingModal) == 0x000000, "Member 'W_CommanderProfileSelect_C_DeleteSave::CallingModal' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_DeleteSave, TextEntry) == 0x000008, "Member 'W_CommanderProfileSelect_C_DeleteSave::TextEntry' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.ExecuteUbergraph_W_CommanderProfileSelect
// 0x0270 (0x0270 - 0x0000)
struct W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UStandardModal* CallingModal)> K2Node_CreateDelegate_OutputDelegate;        // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0020(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0070(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0080(0x0018)()
	class UW_Button_C*                            K2Node_ComponentBoundEvent_Button;                 // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_StandardModal_C* CallingModal, class FText TextEntry)> K2Node_CreateDelegate_OutputDelegate_1; // 0x00A0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              K2Node_CustomEvent_TriggeringProfileCard_1;        // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Hovered;                        // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x00C0(0x0018)(ConstParm)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x00D8(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_115[0x3];                                      // 0x0115(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_124[0x4];                                      // 0x0124(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_StandardModal_C*                     CallFunc_Create_ReturnValue;                       // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommanderProfile*                      CallFunc_LoadProfile_ReturnValue;                  // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_1;                              // 0x0140(0x0018)(ConstParm)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0158(0x0008)(NoDestructor)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16A[0x2];                                      // 0x016A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* TriggeringProfileCard, bool Hovered)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0170(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UW_CommanderProfileCard_C*              K2Node_CustomEvent_TriggeringProfileCard;          // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UW_CommanderProfileCard_C* TriggeringProfileCard)> K2Node_CreateDelegate_OutputDelegate_3; // 0x0188(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UW_StandardModal_C*                     K2Node_CustomEvent_CallingModal_1;                 // 0x0198(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_TextEntry;                      // 0x01A0(0x0018)()
	class UStandardModal*                         K2Node_CustomEvent_CallingModal;                   // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_2;                              // 0x01C0(0x0018)(ConstParm)
	struct FVector2D                              Temp_struct_Variable;                              // 0x01D8(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UW_CommanderProfileCard_C*>      K2Node_MakeArray_Array_1;                          // 0x01E8(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item;                           // 0x01F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0200(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0208(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x020C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20D[0x3];                                      // 0x020D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UW_CommanderProfileCard_C*>      K2Node_MakeArray_Array_2;                          // 0x0210(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_1;                         // 0x0220(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22C[0x4];                                      // 0x022C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UW_CommanderProfileCard_C*>      K2Node_MakeArray_Array_3;                          // 0x0230(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item_2;                         // 0x0240(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x024C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24D[0x3];                                      // 0x024D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_ButtonID;               // 0x0258(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0269(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26A[0x2];                                      // 0x026A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x026C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect");
static_assert(sizeof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect) == 0x000270, "Wrong size on W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, EntryPoint) == 0x000000, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue) == 0x000004, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Conv_IntToInt64_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeStruct_FormatArgumentData) == 0x000020, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeArray_Array) == 0x000070, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Format_ReturnValue) == 0x000080, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_ComponentBoundEvent_Button) == 0x000098, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000A0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_TriggeringProfileCard_1) == 0x0000B0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_TriggeringProfileCard_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_Hovered) == 0x0000B8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_Hovered' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_text_Variable) == 0x0000C0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_Event_MyGeometry) == 0x0000D8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_Event_InDeltaTime) == 0x000110, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue) == 0x000114, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable) == 0x000118, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_1) == 0x00011C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable) == 0x000120, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Create_ReturnValue) == 0x000128, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_LoadProfile_ReturnValue) == 0x000130, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_LoadProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable_1) == 0x000138, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_text_Variable_1) == 0x000140, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeStruct_SlateChildSize) == 0x000158, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable_1) == 0x000160, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_2) == 0x000164, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_IsValid_ReturnValue_1) == 0x000168, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000169, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Array_Index_Variable_2) == 0x00016C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_2) == 0x000170, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_TriggeringProfileCard) == 0x000180, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_TriggeringProfileCard' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CreateDelegate_OutputDelegate_3) == 0x000188, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_CallingModal_1) == 0x000198, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_CallingModal_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_TextEntry) == 0x0001A0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_TextEntry' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_CustomEvent_CallingModal) == 0x0001B8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_CustomEvent_CallingModal' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_text_Variable_2) == 0x0001C0, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_text_Variable_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_struct_Variable) == 0x0001D8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeArray_Array_1) == 0x0001E8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item) == 0x0001F8, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000200, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue) == 0x000208, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue) == 0x00020C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeArray_Array_2) == 0x000210, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_1) == 0x000220, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue_1) == 0x000228, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_MakeArray_Array_3) == 0x000230, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_MakeArray_Array_3' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Get_Item_2) == 0x000240, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Array_Length_ReturnValue_2) == 0x000248, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue_1) == 0x00024C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, Temp_int_Loop_Counter_Variable_2) == 0x000250, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_ComponentBoundEvent_ButtonID) == 0x000258, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_ComponentBoundEvent_ButtonID' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, K2Node_SwitchString_CmpSuccess) == 0x000268, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::K2Node_SwitchString_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Less_IntInt_ReturnValue_2) == 0x000269, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect, CallFunc_Add_IntInt_ReturnValue_3) == 0x00026C, "Member 'W_CommanderProfileSelect_C_ExecuteUbergraph_W_CommanderProfileSelect::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.FillCardList
// 0x0038 (0x0038 - 0x0000)
struct W_CommanderProfileSelect_C_FillCardList final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0010(0x0008)(NoDestructor)
	class UW_CommanderProfileCard_C*              CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_FillCardList) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_FillCardList");
static_assert(sizeof(W_CommanderProfileSelect_C_FillCardList) == 0x000038, "Wrong size on W_CommanderProfileSelect_C_FillCardList");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'W_CommanderProfileSelect_C_FillCardList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Subtract_IntInt_ReturnValue) == 0x000004, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'W_CommanderProfileSelect_C_FillCardList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, K2Node_MakeStruct_SlateChildSize) == 0x000010, "Member 'W_CommanderProfileSelect_C_FillCardList::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Array_Get_Item) == 0x000018, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000028, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000030, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_FillCardList, CallFunc_Max_ReturnValue) == 0x000034, "Member 'W_CommanderProfileSelect_C_FillCardList::CallFunc_Max_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.OpenDeleteSaveConfirmation
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation final
{
public:
	class UW_CommanderProfileCard_C*              TriggeringProfileCard;                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation");
static_assert(sizeof(W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation");
static_assert(offsetof(W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation, TriggeringProfileCard) == 0x000000, "Member 'W_CommanderProfileSelect_C_OpenDeleteSaveConfirmation::TriggeringProfileCard' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.ProfileHoverStateChange
// 0x0010 (0x0010 - 0x0000)
struct W_CommanderProfileSelect_C_ProfileHoverStateChange final
{
public:
	class UW_CommanderProfileCard_C*              TriggeringProfileCard;                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Hovered;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_ProfileHoverStateChange) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_ProfileHoverStateChange");
static_assert(sizeof(W_CommanderProfileSelect_C_ProfileHoverStateChange) == 0x000010, "Wrong size on W_CommanderProfileSelect_C_ProfileHoverStateChange");
static_assert(offsetof(W_CommanderProfileSelect_C_ProfileHoverStateChange, TriggeringProfileCard) == 0x000000, "Member 'W_CommanderProfileSelect_C_ProfileHoverStateChange::TriggeringProfileCard' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ProfileHoverStateChange, Hovered) == 0x000008, "Member 'W_CommanderProfileSelect_C_ProfileHoverStateChange::Hovered' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.ResetCurrentUnhoverFill
// 0x0018 (0x0018 - 0x0000)
struct W_CommanderProfileSelect_C_ResetCurrentUnhoverFill final
{
public:
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0000(0x0008)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_ResetCurrentUnhoverFill");
static_assert(sizeof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill) == 0x000018, "Wrong size on W_CommanderProfileSelect_C_ResetCurrentUnhoverFill");
static_assert(offsetof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill, K2Node_MakeStruct_SlateChildSize) == 0x000000, "Member 'W_CommanderProfileSelect_C_ResetCurrentUnhoverFill::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_ResetCurrentUnhoverFill::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_ResetCurrentUnhoverFill, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue) == 0x000010, "Member 'W_CommanderProfileSelect_C_ResetCurrentUnhoverFill::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.SetCurrentHoverFill
// 0x0018 (0x0018 - 0x0000)
struct W_CommanderProfileSelect_C_SetCurrentHoverFill final
{
public:
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0000(0x0008)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_SetCurrentHoverFill) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_SetCurrentHoverFill");
static_assert(sizeof(W_CommanderProfileSelect_C_SetCurrentHoverFill) == 0x000018, "Wrong size on W_CommanderProfileSelect_C_SetCurrentHoverFill");
static_assert(offsetof(W_CommanderProfileSelect_C_SetCurrentHoverFill, K2Node_MakeStruct_SlateChildSize) == 0x000000, "Member 'W_CommanderProfileSelect_C_SetCurrentHoverFill::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_SetCurrentHoverFill, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'W_CommanderProfileSelect_C_SetCurrentHoverFill::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_SetCurrentHoverFill, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue) == 0x000010, "Member 'W_CommanderProfileSelect_C_SetCurrentHoverFill::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.Tick
// 0x003C (0x003C - 0x0000)
struct W_CommanderProfileSelect_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_Tick) == 0x000004, "Wrong alignment on W_CommanderProfileSelect_C_Tick");
static_assert(sizeof(W_CommanderProfileSelect_C_Tick) == 0x00003C, "Wrong size on W_CommanderProfileSelect_C_Tick");
static_assert(offsetof(W_CommanderProfileSelect_C_Tick, MyGeometry) == 0x000000, "Member 'W_CommanderProfileSelect_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(W_CommanderProfileSelect_C_Tick, InDeltaTime) == 0x000038, "Member 'W_CommanderProfileSelect_C_Tick::InDeltaTime' has a wrong offset!");

// Function W_CommanderProfileSelect.W_CommanderProfileSelect_C.BP_GetDesiredFocusTarget
// 0x0008 (0x0008 - 0x0000)
struct W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong size on W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'W_CommanderProfileSelect_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");

}

