#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_EmptySlot

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_EmptySlot.W_EmptySlot_C
// 0x0008 (0x02C8 - 0x02C0)
class UW_EmptySlot_C final : public UUserWidget
{
public:
	class UButton*                                FocusOnButton;                                     // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_EmptySlot_C">();
	}
	static class UW_EmptySlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_EmptySlot_C>();
	}
};
static_assert(alignof(UW_EmptySlot_C) == 0x000008, "Wrong alignment on UW_EmptySlot_C");
static_assert(sizeof(UW_EmptySlot_C) == 0x0002C8, "Wrong size on UW_EmptySlot_C");
static_assert(offsetof(UW_EmptySlot_C, FocusOnButton) == 0x0002C0, "Member 'UW_EmptySlot_C::FocusOnButton' has a wrong offset!");

}

