#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_HelmetAttachmentPoint

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_HelmetAttachmentPoint.W_HelmetAttachmentPoint_C.ExecuteUbergraph_W_HelmetAttachmentPoint
// 0x0040 (0x0040 - 0x0000)
struct W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0008(0x0018)()
	class ABasePlayer_C*                          K2Node_DynamicCast_AsBase_Player;                  // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ACyberneticsSwat_V2_C*                  K2Node_DynamicCast_AsCybernetics_Swat_V2;          // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue_1;       // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint) == 0x000008, "Wrong alignment on W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint");
static_assert(sizeof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint) == 0x000040, "Wrong size on W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, EntryPoint) == 0x000000, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000005, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, CallFunc_Conv_StringToText_ReturnValue) == 0x000008, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, K2Node_DynamicCast_AsBase_Player) == 0x000020, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::K2Node_DynamicCast_AsBase_Player' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000029, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, K2Node_DynamicCast_AsCybernetics_Swat_V2) == 0x000030, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::K2Node_DynamicCast_AsCybernetics_Swat_V2' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint, CallFunc_K2_AttachToComponent_ReturnValue_1) == 0x000039, "Member 'W_HelmetAttachmentPoint_C_ExecuteUbergraph_W_HelmetAttachmentPoint::CallFunc_K2_AttachToComponent_ReturnValue_1' has a wrong offset!");

}

