#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Loadout_ItemList

#include "Basic.hpp"

#include "W_Loadout_ItemList_classes.hpp"
#include "W_Loadout_ItemList_parameters.hpp"


namespace SDK
{

// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AmmoItemClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AmmoItemClicked(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AmmoItemClicked");

	Params::W_Loadout_ItemList_C_AmmoItemClicked Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AmmoItemDoubleClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AmmoItemDoubleClicked(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AmmoItemDoubleClicked");

	Params::W_Loadout_ItemList_C_AmmoItemDoubleClicked Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AmmoItemHovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AmmoItemHovered(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AmmoItemHovered");

	Params::W_Loadout_ItemList_C_AmmoItemHovered Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AmmoItemUnhovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TriggeringItem                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AmmoItemUnhovered(class UW_LoadoutSlot_C* TriggeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AmmoItemUnhovered");

	Params::W_Loadout_ItemList_C_AmmoItemUnhovered Parms{};

	Parms.TriggeringItem = TriggeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ArmourMaterialClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ArmourMaterialClicked(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ArmourMaterialClicked");

	Params::W_Loadout_ItemList_C_ArmourMaterialClicked Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ArmourMaterialDoubleClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ArmourMaterialDoubleClicked(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ArmourMaterialDoubleClicked");

	Params::W_Loadout_ItemList_C_ArmourMaterialDoubleClicked Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ArmourMaterialHovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ArmourMaterialHovered(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ArmourMaterialHovered");

	Params::W_Loadout_ItemList_C_ArmourMaterialHovered Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ArmourMaterialUnhovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TriggeringItem                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ArmourMaterialUnhovered(class UW_LoadoutSlot_C* TriggeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ArmourMaterialUnhovered");

	Params::W_Loadout_ItemList_C_ArmourMaterialUnhovered Parms{};

	Parms.TriggeringItem = TriggeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AttachmentItemClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_Attachment_C*      TriggeringAttachment                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AttachmentItemClicked(class UW_LoadoutSlot_Attachment_C* TriggeringAttachment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AttachmentItemClicked");

	Params::W_Loadout_ItemList_C_AttachmentItemClicked Parms{};

	Parms.TriggeringAttachment = TriggeringAttachment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AttachmentItemHovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_Attachment_C*      TriggeringAttachment                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AttachmentItemHovered(class UW_LoadoutSlot_Attachment_C* TriggeringAttachment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AttachmentItemHovered");

	Params::W_Loadout_ItemList_C_AttachmentItemHovered Parms{};

	Parms.TriggeringAttachment = TriggeringAttachment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.AttachmentItemUnhovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_Attachment_C*      TriggeringAttachment                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::AttachmentItemUnhovered(class UW_LoadoutSlot_Attachment_C* TriggeringAttachment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "AttachmentItemUnhovered");

	Params::W_Loadout_ItemList_C_AttachmentItemUnhovered Parms{};

	Parms.TriggeringAttachment = TriggeringAttachment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.BackPage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Handled                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::BackPage(bool* Handled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "BackPage");

	Params::W_Loadout_ItemList_C_BackPage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Handled != nullptr)
		*Handled = Parms.Handled;
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.BndEvt__W_Loadout_ItemList_ItemScrollBox_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   CurrentOffset_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::BndEvt__W_Loadout_ItemList_ItemScrollBox_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature(float CurrentOffset_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "BndEvt__W_Loadout_ItemList_ItemScrollBox_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature");

	Params::W_Loadout_ItemList_C_BndEvt__W_Loadout_ItemList_ItemScrollBox_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature Parms{};

	Parms.CurrentOffset_0 = CurrentOffset_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ChangePage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             PageName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ChangePage(class FName PageName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ChangePage");

	Params::W_Loadout_ItemList_C_ChangePage Parms{};

	Parms.PageName = PageName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Loadout_ItemList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.CreateAmmoLoadoutWidgetItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             AmmoType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UScrollBoxSlot**                  AsScroll_Box_Slot                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UW_LoadoutSlot_C**                LoadoutSlotWidget                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::CreateAmmoLoadoutWidgetItem(class FName AmmoType, class UClass* Weapon, class UScrollBoxSlot** AsScroll_Box_Slot, class UW_LoadoutSlot_C** LoadoutSlotWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "CreateAmmoLoadoutWidgetItem");

	Params::W_Loadout_ItemList_C_CreateAmmoLoadoutWidgetItem Parms{};

	Parms.AmmoType = AmmoType;
	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);

	if (AsScroll_Box_Slot != nullptr)
		*AsScroll_Box_Slot = Parms.AsScroll_Box_Slot;

	if (LoadoutSlotWidget != nullptr)
		*LoadoutSlotWidget = Parms.LoadoutSlotWidget;
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.CreateArmourMaterialLoadoutWidgetItem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UArmourMaterial*                  ArmourMaterial                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UScrollBoxSlot**                  AsScroll_Box_Slot                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UW_LoadoutSlot_C**                LoadoutSlotWidget                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::CreateArmourMaterialLoadoutWidgetItem(class UArmourMaterial* ArmourMaterial, class UScrollBoxSlot** AsScroll_Box_Slot, class UW_LoadoutSlot_C** LoadoutSlotWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "CreateArmourMaterialLoadoutWidgetItem");

	Params::W_Loadout_ItemList_C_CreateArmourMaterialLoadoutWidgetItem Parms{};

	Parms.ArmourMaterial = ArmourMaterial;

	UObject::ProcessEvent(Func, &Parms);

	if (AsScroll_Box_Slot != nullptr)
		*AsScroll_Box_Slot = Parms.AsScroll_Box_Slot;

	if (LoadoutSlotWidget != nullptr)
		*LoadoutSlotWidget = Parms.LoadoutSlotWidget;
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.CreateLoadoutWidgetItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ItemData                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UScrollBoxSlot**                  AsScroll_Box_Slot                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UW_LoadoutSlot_C**                LoadoutSlotWidget                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::CreateLoadoutWidgetItem(class UClass* ItemData, class UScrollBoxSlot** AsScroll_Box_Slot, class UW_LoadoutSlot_C** LoadoutSlotWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "CreateLoadoutWidgetItem");

	Params::W_Loadout_ItemList_C_CreateLoadoutWidgetItem Parms{};

	Parms.ItemData = ItemData;

	UObject::ProcessEvent(Func, &Parms);

	if (AsScroll_Box_Slot != nullptr)
		*AsScroll_Box_Slot = Parms.AsScroll_Box_Slot;

	if (LoadoutSlotWidget != nullptr)
		*LoadoutSlotWidget = Parms.LoadoutSlotWidget;
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ExecuteUbergraph_W_Loadout_ItemList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ExecuteUbergraph_W_Loadout_ItemList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ExecuteUbergraph_W_Loadout_ItemList");

	Params::W_Loadout_ItemList_C_ExecuteUbergraph_W_Loadout_ItemList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.GetItemArrayBySlot
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::GetItemArrayBySlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "GetItemArrayBySlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.HeaderSubpageNavigation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             OptionNameID                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::HeaderSubpageNavigation(class FName OptionNameID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "HeaderSubpageNavigation");

	Params::W_Loadout_ItemList_C_HeaderSubpageNavigation Parms{};

	Parms.OptionNameID = OptionNameID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.Hide
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Collapse                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::Hide(double Delay, bool Collapse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "Hide");

	Params::W_Loadout_ItemList_C_Hide Parms{};

	Parms.Delay = Delay;
	Parms.Collapse = Collapse;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.HideList
// (BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::HideList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "HideList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.InitializeAmmoList
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ExcludedAmmoType_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::InitializeAmmoList(class FName ExcludedAmmoType_0, class UClass* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "InitializeAmmoList");

	Params::W_Loadout_ItemList_C_InitializeAmmoList Parms{};

	Parms.ExcludedAmmoType_0 = ExcludedAmmoType_0;
	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.InitializeArmourMaterialList
// (BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::InitializeArmourMaterialList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "InitializeArmourMaterialList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.InitializeAttachmentList
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ItemData                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EWeaponAttachmentType                   AttachmentType                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::InitializeAttachmentList(class UClass* ItemData, EWeaponAttachmentType AttachmentType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "InitializeAttachmentList");

	Params::W_Loadout_ItemList_C_InitializeAttachmentList Parms{};

	Parms.ItemData = ItemData;
	Parms.AttachmentType = AttachmentType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.InitializeDeployableList
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const EItemCategory                     LoadoutSlot                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct LoadoutCategory::FLoadoutCategory>&GearCategoryClasses                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const TArray<class UClass*>&            ExcludedItems_0                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_Loadout_ItemList_C::InitializeDeployableList(const EItemCategory LoadoutSlot, const TArray<struct LoadoutCategory::FLoadoutCategory>& GearCategoryClasses, const TArray<class UClass*>& ExcludedItems_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "InitializeDeployableList");

	Params::W_Loadout_ItemList_C_InitializeDeployableList Parms{};

	Parms.LoadoutSlot = LoadoutSlot;
	Parms.GearCategoryClasses = std::move(GearCategoryClasses);
	Parms.ExcludedItems_0 = std::move(ExcludedItems_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.InitializeLoadoutList
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const EItemCategory                     LoadoutSlot                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct LoadoutCategory::FLoadoutCategory>&GearCategoryClasses                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_Loadout_ItemList_C::InitializeLoadoutList(const EItemCategory LoadoutSlot, const TArray<struct LoadoutCategory::FLoadoutCategory>& GearCategoryClasses)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "InitializeLoadoutList");

	Params::W_Loadout_ItemList_C_InitializeLoadoutList Parms{};

	Parms.LoadoutSlot = LoadoutSlot;
	Parms.GearCategoryClasses = std::move(GearCategoryClasses);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.LoadoutItemClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::LoadoutItemClicked(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "LoadoutItemClicked");

	Params::W_Loadout_ItemList_C_LoadoutItemClicked Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.LoadoutItemDoubleClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TrigeringItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::LoadoutItemDoubleClicked(class UW_LoadoutSlot_C* TrigeringItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "LoadoutItemDoubleClicked");

	Params::W_Loadout_ItemList_C_LoadoutItemDoubleClicked Parms{};

	Parms.TrigeringItem = TrigeringItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.LoadoutItemHovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TriggeringSlot                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::LoadoutItemHovered(class UW_LoadoutSlot_C* TriggeringSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "LoadoutItemHovered");

	Params::W_Loadout_ItemList_C_LoadoutItemHovered Parms{};

	Parms.TriggeringSlot = TriggeringSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.LoadoutItemUnhovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 TriggeringSlot                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::LoadoutItemUnhovered(class UW_LoadoutSlot_C* TriggeringSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "LoadoutItemUnhovered");

	Params::W_Loadout_ItemList_C_LoadoutItemUnhovered Parms{};

	Parms.TriggeringSlot = TriggeringSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.OpenList
// (BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::OpenList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "OpenList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.PopulateAmmo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>&                    AmmoTypes                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UClass*                           Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::PopulateAmmo(TArray<class FName>& AmmoTypes, class UClass* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "PopulateAmmo");

	Params::W_Loadout_ItemList_C_PopulateAmmo Parms{};

	Parms.AmmoTypes = std::move(AmmoTypes);
	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);

	AmmoTypes = std::move(Parms.AmmoTypes);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.PopulateArmourMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::PopulateArmourMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "PopulateArmourMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.PopulateAttachments
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UClass*>&                  Attachments_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_Loadout_ItemList_C::PopulateAttachments(TArray<class UClass*>& Attachments_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "PopulateAttachments");

	Params::W_Loadout_ItemList_C_PopulateAttachments Parms{};

	Parms.Attachments_0 = std::move(Attachments_0);

	UObject::ProcessEvent(Func, &Parms);

	Attachments_0 = std::move(Parms.Attachments_0);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.PopulateItems
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct LoadoutCategory::FLoadoutCategory>&GearCategoryClasses                                    (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_Loadout_ItemList_C::PopulateItems(TArray<struct LoadoutCategory::FLoadoutCategory>& GearCategoryClasses)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "PopulateItems");

	Params::W_Loadout_ItemList_C_PopulateItems Parms{};

	Parms.GearCategoryClasses = std::move(GearCategoryClasses);

	UObject::ProcessEvent(Func, &Parms);

	GearCategoryClasses = std::move(Parms.GearCategoryClasses);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.PopulateSubnav
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::PopulateSubnav()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "PopulateSubnav");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "PreConstruct");

	Params::W_Loadout_ItemList_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.RefreshEquipped
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSavedLoadout&             ActiveLoadout_0                                        (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    RefreshAttachments                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::RefreshEquipped(const struct FSavedLoadout& ActiveLoadout_0, bool RefreshAttachments)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "RefreshEquipped");

	Params::W_Loadout_ItemList_C_RefreshEquipped Parms{};

	Parms.ActiveLoadout_0 = std::move(ActiveLoadout_0);
	Parms.RefreshAttachments = RefreshAttachments;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.RefreshEquippedAmmo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::RefreshEquippedAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "RefreshEquippedAmmo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.RefreshEquippedArmourMaterial
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::RefreshEquippedArmourMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "RefreshEquippedArmourMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.RefreshEquippedAttachments
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::RefreshEquippedAttachments()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "RefreshEquippedAttachments");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.RefreshEquippedItems
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::RefreshEquippedItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "RefreshEquippedItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.Reveal
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::Reveal(double Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "Reveal");

	Params::W_Loadout_ItemList_C_Reveal Parms{};

	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollOpenedToEquipped
// (BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::ScrollOpenedToEquipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollOpenedToEquipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToEquipped
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::ScrollToEquipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToEquipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToNextItem
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::ScrollToNextItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToNextItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToNextPage
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::ScrollToNextPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToNextPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToPage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Page                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ScrollToPage(int32 Page)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToPage");

	Params::W_Loadout_ItemList_C_ScrollToPage Parms{};

	Parms.Page = Page;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToPreviousItem
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::ScrollToPreviousItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToPreviousItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToPreviousPage
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::ScrollToPreviousPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToPreviousPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.ScrollToTargetIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ItemIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::ScrollToTargetIndex(int32 ItemIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "ScrollToTargetIndex");

	Params::W_Loadout_ItemList_C_ScrollToTargetIndex Parms{};

	Parms.ItemIndex = ItemIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.SetInputMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsGamepad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::SetInputMode(bool IsGamepad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "SetInputMode");

	Params::W_Loadout_ItemList_C_SetInputMode Parms{};

	Parms.IsGamepad = IsGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.SetListItemPadding
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsFirstItem                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UScrollBoxSlot*                   ScrollBoxSlotItem                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::SetListItemPadding(bool IsFirstItem, class UScrollBoxSlot* ScrollBoxSlotItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "SetListItemPadding");

	Params::W_Loadout_ItemList_C_SetListItemPadding Parms{};

	Parms.IsFirstItem = IsFirstItem;
	Parms.ScrollBoxSlotItem = ScrollBoxSlotItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.SetLoadoutWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_Loadout_C*                     LoadoutWidget                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::SetLoadoutWidget(class UW_Loadout_C* LoadoutWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "SetLoadoutWidget");

	Params::W_Loadout_ItemList_C_SetLoadoutWidget Parms{};

	Parms.LoadoutWidget = LoadoutWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.SetupScrollPagination
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::SetupScrollPagination()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "SetupScrollPagination");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.SortItems
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::SortItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "SortItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.SubnavButtonClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_Button_C*                      TriggeringButton                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::SubnavButtonClicked(class UW_Button_C* TriggeringButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "SubnavButtonClicked");

	Params::W_Loadout_ItemList_C_SubnavButtonClicked Parms{};

	Parms.TriggeringButton = TriggeringButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "Tick");

	Params::W_Loadout_ItemList_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.UpdateActiveLoadout
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSavedLoadout&             ActiveLoadout_0                                        (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_Loadout_ItemList_C::UpdateActiveLoadout(const struct FSavedLoadout& ActiveLoadout_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "UpdateActiveLoadout");

	Params::W_Loadout_ItemList_C_UpdateActiveLoadout Parms{};

	Parms.ActiveLoadout_0 = std::move(ActiveLoadout_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.UpdateCurrentItemMap
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TMap<EItemCategory, class UClass*>&ItemCategory                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_Loadout_ItemList_C::UpdateCurrentItemMap(const TMap<EItemCategory, class UClass*>& ItemCategory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "UpdateCurrentItemMap");

	Params::W_Loadout_ItemList_C_UpdateCurrentItemMap Parms{};

	Parms.ItemCategory = std::move(ItemCategory);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.UpdateCurrentSlot
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_LoadoutSlot_C*                 CurrentSlot                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::UpdateCurrentSlot(class UW_LoadoutSlot_C* CurrentSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "UpdateCurrentSlot");

	Params::W_Loadout_ItemList_C_UpdateCurrentSlot Parms{};

	Parms.CurrentSlot = CurrentSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.UpdateScrollPage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Loadout_ItemList_C::UpdateScrollPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "UpdateScrollPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Loadout_ItemList.W_Loadout_ItemList_C.GetFocusTarget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget**                         Focus                                                  (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_Loadout_ItemList_C::GetFocusTarget(class UWidget** Focus) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Loadout_ItemList_C", "GetFocusTarget");

	Params::W_Loadout_ItemList_C_GetFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Focus != nullptr)
		*Focus = Parms.Focus;
}

}

