#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PauseMenu_Wrapper

#include "Basic.hpp"

#include "AdvancedSessions_structs.hpp"


namespace SDK::Params
{

// Function W_PauseMenu_Wrapper.W_PauseMenu_Wrapper_C.ExecuteUbergraph_W_PauseMenu_Wrapper
// 0x0138 (0x0138 - 0x0000)
struct W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ATrainingGM*                            K2Node_DynamicCast_AsTraining_GM;                  // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACoopGM*                                K2Node_DynamicCast_AsCoop_GM;                      // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x002C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x003C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x004C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ConsoleLobbyManager_C*               CallFunc_BP_AddWidget_ReturnValue;                 // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_Options_UE5_C*                       CallFunc_BP_AddWidget_ReturnValue_1;               // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonActivatableWidget*               CallFunc_GetActiveWidget_ReturnValue;              // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_PauseMenu_V2_C*                      K2Node_DynamicCast_AsW_Pause_Menu_V2;              // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0084(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue_1;                // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AReadyOrNotGameMode*                    K2Node_DynamicCast_AsReady_or_Not_Game_Mode;       // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x3];                                       // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x00AC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x00C8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EBlueprintResultSwitch                        CallFunc_ShowInviteUI_Result;                      // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DA[0x2];                                       // 0x00DA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x00DC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UReadyOrNotGameInstance*                K2Node_DynamicCast_AsReady_or_Not_Game_Instance;   // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UReadyOrNotGameInstance*                CallFunc_GetReadyOrNotGameInstance_ReturnValue;    // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0128(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper) == 0x000008, "Wrong alignment on W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper");
static_assert(sizeof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper) == 0x000138, "Wrong size on W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, EntryPoint) == 0x000000, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetGameMode_ReturnValue) == 0x000008, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_AsTraining_GM) == 0x000010, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_AsTraining_GM' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_AsCoop_GM) == 0x000020, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_AsCoop_GM' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_bSuccess_1) == 0x000028, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate) == 0x00002C, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_1) == 0x00003C, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_2) == 0x00004C, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_BP_AddWidget_ReturnValue) == 0x000060, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_BP_AddWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_BP_AddWidget_ReturnValue_1) == 0x000068, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_BP_AddWidget_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetActiveWidget_ReturnValue) == 0x000070, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_AsW_Pause_Menu_V2) == 0x000078, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_AsW_Pause_Menu_V2' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_bSuccess_2) == 0x000080, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_3) == 0x000084, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetGameMode_ReturnValue_1) == 0x000098, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetGameMode_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_AsReady_or_Not_Game_Mode) == 0x0000A0, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_AsReady_or_Not_Game_Mode' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_bSuccess_3) == 0x0000A8, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_4) == 0x0000AC, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetOwningPlayer_ReturnValue) == 0x0000C0, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_5) == 0x0000C8, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_ShowInviteUI_Result) == 0x0000D8, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_ShowInviteUI_Result' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_SwitchEnum_CmpSuccess) == 0x0000D9, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_6) == 0x0000DC, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x0000F0, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetGameInstance_ReturnValue) == 0x0000F8, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_AsReady_or_Not_Game_Instance) == 0x000100, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_AsReady_or_Not_Game_Instance' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_DynamicCast_bSuccess_4) == 0x000108, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_GetReadyOrNotGameInstance_ReturnValue) == 0x000110, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_GetReadyOrNotGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, CallFunc_Concat_StrStr_ReturnValue) == 0x000118, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper, K2Node_CreateDelegate_OutputDelegate_7) == 0x000128, "Member 'W_PauseMenu_Wrapper_C_ExecuteUbergraph_W_PauseMenu_Wrapper::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");

}

