#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayersList_Entry

#include "Basic.hpp"

#include "W_PlayersList_Entry_classes.hpp"
#include "W_PlayersList_Entry_parameters.hpp"


namespace SDK
{

// Function W_PlayersList_Entry.W_PlayersList_Entry_C.bLock
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_StandardModal_C*               CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FText&                      TextEntry                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_PlayersList_Entry_C::bLock(class UW_StandardModal_C* CallingModal, const class FText& TextEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "bLock");

	Params::W_PlayersList_Entry_C_bLock Parms{};

	Parms.CallingModal = CallingModal;
	Parms.TextEntry = std::move(TextEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BaseButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_30_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_30_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_30_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_30_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BlockButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_24_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_BlockButtonGamepad_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_CommonButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_CommonButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_CommonButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_CommonButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_29_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_29_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_29_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_KickButton_K2Node_ComponentBoundEvent_29_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_KickButtonGamepad_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_28_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_28_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_28_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_MuteButton_K2Node_ComponentBoundEvent_28_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_27_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_27_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_27_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_27_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_MuteButtonGamepad_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_31_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_31_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_31_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ReportButton_K2Node_ComponentBoundEvent_31_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_25_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_25_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_25_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_25_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ReportButtonGamepad_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_32_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_32_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_32_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ViewProfileButton_K2Node_ComponentBoundEvent_32_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_26_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_26_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_26_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_26_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_ViewProfileButtonGamepad_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_20_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_20_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_20_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_20_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_22_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_22_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_22_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_22_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_23_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_23_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_23_CommonButtonBaseClicked__DelegateSignature");

	Params::W_PlayersList_Entry_C_BndEvt__W_PlayersList_Entry_W_InputActionButton_K2Node_ComponentBoundEvent_23_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.Cancel kick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStandardModal*                   CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::Cancel_kick(class UStandardModal* CallingModal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "Cancel kick");

	Params::W_PlayersList_Entry_C_Cancel_kick Parms{};

	Parms.CallingModal = CallingModal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.CancelBlock
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStandardModal*                   CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::CancelBlock(class UStandardModal* CallingModal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "CancelBlock");

	Params::W_PlayersList_Entry_C_CancelBlock Parms{};

	Parms.CallingModal = CallingModal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_PlayersList_Entry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.ExecuteUbergraph_W_PlayersList_Entry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::ExecuteUbergraph_W_PlayersList_Entry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "ExecuteUbergraph_W_PlayersList_Entry");

	Params::W_PlayersList_Entry_C_ExecuteUbergraph_W_PlayersList_Entry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.GetColorAndOpacity_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UW_PlayersList_Entry_C::GetColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "GetColorAndOpacity_0");

	Params::W_PlayersList_Entry_C_GetColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.Initialise Popup
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLobbyPlayer&              Player_Name                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      TextFormat                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      ButtonText                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// class UW_StandardModal_C**              OutputPopUp                                            (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::Initialise_Popup(const struct FLobbyPlayer& Player_Name, const class FText& TextFormat, const class FText& ButtonText, class UW_StandardModal_C** OutputPopUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "Initialise Popup");

	Params::W_PlayersList_Entry_C_Initialise_Popup Parms{};

	Parms.Player_Name = std::move(Player_Name);
	Parms.TextFormat = std::move(TextFormat);
	Parms.ButtonText = std::move(ButtonText);

	UObject::ProcessEvent(Func, &Parms);

	if (OutputPopUp != nullptr)
		*OutputPopUp = Parms.OutputPopUp;
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.kick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_StandardModal_C*               CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FText&                      TextEntry                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_PlayersList_Entry_C::kick(class UW_StandardModal_C* CallingModal, const class FText& TextEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "kick");

	Params::W_PlayersList_Entry_C_kick Parms{};

	Parms.CallingModal = CallingModal;
	Parms.TextEntry = std::move(TextEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.OnFail_A80FE7774956E9E96F18519FA7E7A60C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2DDynamic*                Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::OnFail_A80FE7774956E9E96F18519FA7E7A60C(class UTexture2DDynamic* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "OnFail_A80FE7774956E9E96F18519FA7E7A60C");

	Params::W_PlayersList_Entry_C_OnFail_A80FE7774956E9E96F18519FA7E7A60C Parms{};

	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.OnSuccess_A80FE7774956E9E96F18519FA7E7A60C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2DDynamic*                Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_PlayersList_Entry_C::OnSuccess_A80FE7774956E9E96F18519FA7E7A60C(class UTexture2DDynamic* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "OnSuccess_A80FE7774956E9E96F18519FA7E7A60C");

	Params::W_PlayersList_Entry_C_OnSuccess_A80FE7774956E9E96F18519FA7E7A60C Parms{};

	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlayersList_Entry.W_PlayersList_Entry_C.RefreshPlayer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLobbyPlayer&              Player_0                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_PlayersList_Entry_C::RefreshPlayer(const struct FLobbyPlayer& Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlayersList_Entry_C", "RefreshPlayer");

	Params::W_PlayersList_Entry_C_RefreshPlayer Parms{};

	Parms.Player_0 = std::move(Player_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

