#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlanningMap_BreachPoint_Info_EquipmentEntry

#include "Basic.hpp"

#include "W_PlanningMap_BreachPoint_Info_EquipmentEntry_classes.hpp"
#include "W_PlanningMap_BreachPoint_Info_EquipmentEntry_parameters.hpp"


namespace SDK
{

// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.BndEvt__W_Button_K2Node_ComponentBoundEvent_0_Hovered__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::BndEvt__W_Button_K2Node_ComponentBoundEvent_0_Hovered__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "BndEvt__W_Button_K2Node_ComponentBoundEvent_0_Hovered__DelegateSignature");

	Params::W_PlanningMap_BreachPoint_Info_EquipmentEntry_C_BndEvt__W_Button_K2Node_ComponentBoundEvent_0_Hovered__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.BndEvt__W_Button_K2Node_ComponentBoundEvent_1_Unhovered__DelegateSignature
// (BlueprintEvent)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::BndEvt__W_Button_K2Node_ComponentBoundEvent_1_Unhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "BndEvt__W_Button_K2Node_ComponentBoundEvent_1_Unhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.BndEvt__W_Button_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature
// (BlueprintEvent)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::BndEvt__W_Button_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "BndEvt__W_Button_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.BndEvt__W_Button_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::BndEvt__W_Button_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "BndEvt__W_Button_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature");

	Params::W_PlanningMap_BreachPoint_Info_EquipmentEntry_C_BndEvt__W_Button_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.BndEvt__W_Button_K2Node_ComponentBoundEvent_4_Released__DelegateSignature
// (BlueprintEvent)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::BndEvt__W_Button_K2Node_ComponentBoundEvent_4_Released__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "BndEvt__W_Button_K2Node_ComponentBoundEvent_4_Released__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.ExecuteUbergraph_W_PlanningMap_BreachPoint_Info_EquipmentEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::ExecuteUbergraph_W_PlanningMap_BreachPoint_Info_EquipmentEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "ExecuteUbergraph_W_PlanningMap_BreachPoint_Info_EquipmentEntry");

	Params::W_PlanningMap_BreachPoint_Info_EquipmentEntry_C_ExecuteUbergraph_W_PlanningMap_BreachPoint_Info_EquipmentEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_PlanningMap_BreachPoint_Info_EquipmentEntry.W_PlanningMap_BreachPoint_Info_EquipmentEntry_C.OnLoaded_0AA3E177468D68E03944E59A03A2CFB4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_PlanningMap_BreachPoint_Info_EquipmentEntry_C::OnLoaded_0AA3E177468D68E03944E59A03A2CFB4(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_PlanningMap_BreachPoint_Info_EquipmentEntry_C", "OnLoaded_0AA3E177468D68E03944E59A03A2CFB4");

	Params::W_PlanningMap_BreachPoint_Info_EquipmentEntry_C_OnLoaded_0AA3E177468D68E03944E59A03A2CFB4 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}

}

