#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PointSaveSlot

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PointSaveSlot.W_PointSaveSlot_C
// 0x0070 (0x0330 - 0x02C0)
class UW_PointSaveSlot_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                DeleteButton;                                      // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableName;                                      // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                FocusOnButton;                                     // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                LoadButton;                                        // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SaveButton;                                        // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 Name_0;                                            // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class AP_DebugPawn_C*                         DebugCameraRef;                                    // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<class FString>                         Alphabet;                                          // 0x0308(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         SaveSlotID;                                        // 0x0318(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_31C[0x4];                                      // 0x031C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPointSaveGame_C*                       SaveSlot;                                          // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UW_Main_C*                              W_Main;                                            // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void BndEvt__W_CameraSaveSlot_EditableName_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__W_CameraSaveSlot_SaveButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__W_SimplePointLight_DeleteButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__W_TeleportPoint_TeleportButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
	void Completed_1F7CDDA94F3535E5E9D961A52372BFAF(class USaveGame* SaveGame, bool bSuccess);
	void Construct();
	void ExecuteUbergraph_W_PointSaveSlot(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_PointSaveSlot_C">();
	}
	static class UW_PointSaveSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_PointSaveSlot_C>();
	}
};
static_assert(alignof(UW_PointSaveSlot_C) == 0x000008, "Wrong alignment on UW_PointSaveSlot_C");
static_assert(sizeof(UW_PointSaveSlot_C) == 0x000330, "Wrong size on UW_PointSaveSlot_C");
static_assert(offsetof(UW_PointSaveSlot_C, UberGraphFrame) == 0x0002C0, "Member 'UW_PointSaveSlot_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, DeleteButton) == 0x0002C8, "Member 'UW_PointSaveSlot_C::DeleteButton' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, EditableName) == 0x0002D0, "Member 'UW_PointSaveSlot_C::EditableName' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, FocusOnButton) == 0x0002D8, "Member 'UW_PointSaveSlot_C::FocusOnButton' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, LoadButton) == 0x0002E0, "Member 'UW_PointSaveSlot_C::LoadButton' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, SaveButton) == 0x0002E8, "Member 'UW_PointSaveSlot_C::SaveButton' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, Name_0) == 0x0002F0, "Member 'UW_PointSaveSlot_C::Name_0' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, DebugCameraRef) == 0x000300, "Member 'UW_PointSaveSlot_C::DebugCameraRef' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, Alphabet) == 0x000308, "Member 'UW_PointSaveSlot_C::Alphabet' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, SaveSlotID) == 0x000318, "Member 'UW_PointSaveSlot_C::SaveSlotID' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, SaveSlot) == 0x000320, "Member 'UW_PointSaveSlot_C::SaveSlot' has a wrong offset!");
static_assert(offsetof(UW_PointSaveSlot_C, W_Main) == 0x000328, "Member 'UW_PointSaveSlot_C::W_Main' has a wrong offset!");

}

