#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ReadyRoomWidget

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CommonInput_structs.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK::Params
{

// Function W_ReadyRoomWidget.W_ReadyRoomWidget_C.ExecuteUbergraph_W_ReadyRoomWidget
// 0x0A20 (0x0A20 - 0x0000)
struct W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FCeil_ReturnValue;                        // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0038(0x0018)()
	class AMissionPortal*                         CallFunc_GetActorOfClass_ReturnValue;              // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_Countdown;                      // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPlayersReady_Ready;                    // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPlayersReady_Total;                    // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetPlayersReady_ReturnValue;              // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_1;            // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0078(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00C8(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0118(0x0010)(ReferenceParm)
	class FString                                 CallFunc_GetSelectedMission_OutMissionURL;         // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLevelDataLookupTable                  CallFunc_GetMapDetailsFromName_ReturnValue;        // 0x0140(0x0818)()
	class UTexture2D*                             CallFunc_GetLazyLoadedImage_ReturnValue;           // 0x0958(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bReady;                         // 0x0960(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_961[0x7];                                      // 0x0961(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0968(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_2;          // 0x0970(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(float Countdown)>              K2Node_CreateDelegate_OutputDelegate_3;            // 0x0980(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              K2Node_CustomEvent_bNewInputType;                  // 0x0990(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_991[0x7];                                      // 0x0991(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotPlayerController*            CallFunc_GetReadyOrNotPlayerController_ReturnValue; // 0x0998(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x09A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9A1[0x7];                                      // 0x09A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x09A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ALobbyGS*                               K2Node_DynamicCast_AsLobby_GS;                     // 0x09B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x09B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9B9[0x7];                                      // 0x09B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x09C0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x09D8(0x0018)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x09F0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_CountdownTime;                  // 0x0A00(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AReadyOrNotPlayerController*            CallFunc_GetReadyOrNotPlayerController_ReturnValue_1; // 0x0A08(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUsingGamepad_ReturnValue;               // 0x0A10(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A11[0x7];                                      // 0x0A11(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_VariableSet_Counter_ImplicitCast;           // 0x0A18(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget) == 0x000008, "Wrong alignment on W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget");
static_assert(sizeof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget) == 0x000A20, "Wrong size on W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, EntryPoint) == 0x000000, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetCurrentInputType_ReturnValue) == 0x000020, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CreateDelegate_OutputDelegate_1) == 0x000024, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_FCeil_ReturnValue) == 0x000034, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_FCeil_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_Conv_IntToText_ReturnValue) == 0x000038, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetActorOfClass_ReturnValue) == 0x000050, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CustomEvent_Countdown) == 0x000058, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CustomEvent_Countdown' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetPlayersReady_Ready) == 0x00005C, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetPlayersReady_Ready' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetPlayersReady_Total) == 0x000060, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetPlayersReady_Total' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetPlayersReady_ReturnValue) == 0x000064, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetPlayersReady_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_Conv_IntToInt64_ReturnValue) == 0x000068, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_Conv_IntToInt64_ReturnValue_1) == 0x000070, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_Conv_IntToInt64_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_MakeStruct_FormatArgumentData) == 0x000078, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_MakeStruct_FormatArgumentData_1) == 0x0000C8, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_MakeArray_Array) == 0x000118, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetSelectedMission_OutMissionURL) == 0x000128, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetSelectedMission_OutMissionURL' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_IsEmpty_ReturnValue) == 0x000138, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetMapDetailsFromName_ReturnValue) == 0x000140, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetMapDetailsFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetLazyLoadedImage_ReturnValue) == 0x000958, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetLazyLoadedImage_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CustomEvent_bReady) == 0x000960, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CustomEvent_bReady' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_PlayAnimation_ReturnValue) == 0x000968, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CreateDelegate_OutputDelegate_2) == 0x000970, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CreateDelegate_OutputDelegate_3) == 0x000980, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CustomEvent_bNewInputType) == 0x000990, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CustomEvent_bNewInputType' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetReadyOrNotPlayerController_ReturnValue) == 0x000998, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetReadyOrNotPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0009A0, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetGameState_ReturnValue) == 0x0009A8, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_DynamicCast_AsLobby_GS) == 0x0009B0, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_DynamicCast_AsLobby_GS' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_DynamicCast_bSuccess) == 0x0009B8, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_MakeLiteralText_ReturnValue) == 0x0009C0, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_Format_ReturnValue) == 0x0009D8, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CreateDelegate_OutputDelegate_4) == 0x0009F0, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_CustomEvent_CountdownTime) == 0x000A00, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_CustomEvent_CountdownTime' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_GetReadyOrNotPlayerController_ReturnValue_1) == 0x000A08, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_GetReadyOrNotPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, CallFunc_IsUsingGamepad_ReturnValue) == 0x000A10, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::CallFunc_IsUsingGamepad_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget, K2Node_VariableSet_Counter_ImplicitCast) == 0x000A18, "Member 'W_ReadyRoomWidget_C_ExecuteUbergraph_W_ReadyRoomWidget::K2Node_VariableSet_Counter_ImplicitCast' has a wrong offset!");

// Function W_ReadyRoomWidget.W_ReadyRoomWidget_C.OnCountdownStart
// 0x0004 (0x0004 - 0x0000)
struct W_ReadyRoomWidget_C_OnCountdownStart final
{
public:
	float                                         Countdown;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ReadyRoomWidget_C_OnCountdownStart) == 0x000004, "Wrong alignment on W_ReadyRoomWidget_C_OnCountdownStart");
static_assert(sizeof(W_ReadyRoomWidget_C_OnCountdownStart) == 0x000004, "Wrong size on W_ReadyRoomWidget_C_OnCountdownStart");
static_assert(offsetof(W_ReadyRoomWidget_C_OnCountdownStart, Countdown) == 0x000000, "Member 'W_ReadyRoomWidget_C_OnCountdownStart::Countdown' has a wrong offset!");

// Function W_ReadyRoomWidget.W_ReadyRoomWidget_C.OnInputChange
// 0x0001 (0x0001 - 0x0000)
struct W_ReadyRoomWidget_C_OnInputChange final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ReadyRoomWidget_C_OnInputChange) == 0x000001, "Wrong alignment on W_ReadyRoomWidget_C_OnInputChange");
static_assert(sizeof(W_ReadyRoomWidget_C_OnInputChange) == 0x000001, "Wrong size on W_ReadyRoomWidget_C_OnInputChange");
static_assert(offsetof(W_ReadyRoomWidget_C_OnInputChange, bNewInputType) == 0x000000, "Member 'W_ReadyRoomWidget_C_OnInputChange::bNewInputType' has a wrong offset!");

// Function W_ReadyRoomWidget.W_ReadyRoomWidget_C.OnLocalPlayerReadyChange
// 0x0001 (0x0001 - 0x0000)
struct W_ReadyRoomWidget_C_OnLocalPlayerReadyChange final
{
public:
	bool                                          bReady;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ReadyRoomWidget_C_OnLocalPlayerReadyChange) == 0x000001, "Wrong alignment on W_ReadyRoomWidget_C_OnLocalPlayerReadyChange");
static_assert(sizeof(W_ReadyRoomWidget_C_OnLocalPlayerReadyChange) == 0x000001, "Wrong size on W_ReadyRoomWidget_C_OnLocalPlayerReadyChange");
static_assert(offsetof(W_ReadyRoomWidget_C_OnLocalPlayerReadyChange, bReady) == 0x000000, "Member 'W_ReadyRoomWidget_C_OnLocalPlayerReadyChange::bReady' has a wrong offset!");

// Function W_ReadyRoomWidget.W_ReadyRoomWidget_C.SetCountdownTime
// 0x0008 (0x0008 - 0x0000)
struct W_ReadyRoomWidget_C_SetCountdownTime final
{
public:
	double                                        CountdownTime;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ReadyRoomWidget_C_SetCountdownTime) == 0x000008, "Wrong alignment on W_ReadyRoomWidget_C_SetCountdownTime");
static_assert(sizeof(W_ReadyRoomWidget_C_SetCountdownTime) == 0x000008, "Wrong size on W_ReadyRoomWidget_C_SetCountdownTime");
static_assert(offsetof(W_ReadyRoomWidget_C_SetCountdownTime, CountdownTime) == 0x000000, "Member 'W_ReadyRoomWidget_C_SetCountdownTime::CountdownTime' has a wrong offset!");

// Function W_ReadyRoomWidget.W_ReadyRoomWidget_C.UpdateInputActionTexts
// 0x0110 (0x0110 - 0x0000)
struct W_ReadyRoomWidget_C_UpdateInputActionTexts final
{
public:
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   Temp_struct_Variable;                              // 0x0008(0x0018)(HasGetValueTypeHash)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0028(0x0018)()
	struct FKey                                   CallFunc_GetKeyFromInputActionName_ReturnValue;    // 0x0040(0x0018)(HasGetValueTypeHash)
	class FText                                   CallFunc_FormatPlayerActionText_ReturnValue;       // 0x0058(0x0018)()
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x0078(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_2;            // 0x0090(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x00A8(0x0018)()
	struct FKey                                   CallFunc_GetKeyFromInputActionName_ReturnValue_1;  // 0x00C0(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsValid_ReturnValue;                  // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_Select_Default_1;                           // 0x00E0(0x0018)(HasGetValueTypeHash)
	class FText                                   CallFunc_FormatPlayerActionText_ReturnValue_1;     // 0x00F8(0x0018)()
};
static_assert(alignof(W_ReadyRoomWidget_C_UpdateInputActionTexts) == 0x000008, "Wrong alignment on W_ReadyRoomWidget_C_UpdateInputActionTexts");
static_assert(sizeof(W_ReadyRoomWidget_C_UpdateInputActionTexts) == 0x000110, "Wrong size on W_ReadyRoomWidget_C_UpdateInputActionTexts");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_MakeLiteralByte_ReturnValue) == 0x000000, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, Temp_bool_Variable) == 0x000001, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, Temp_bool_Variable_1) == 0x000002, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, Temp_struct_Variable) == 0x000008, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_MakeLiteralName_ReturnValue) == 0x000020, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_MakeLiteralText_ReturnValue) == 0x000028, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_GetKeyFromInputActionName_ReturnValue) == 0x000040, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_GetKeyFromInputActionName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_FormatPlayerActionText_ReturnValue) == 0x000058, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_FormatPlayerActionText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_Conv_StringToName_ReturnValue) == 0x000070, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_MakeLiteralText_ReturnValue_1) == 0x000078, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_MakeLiteralText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_MakeLiteralText_ReturnValue_2) == 0x000090, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_MakeLiteralText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, K2Node_Select_Default) == 0x0000A8, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_GetKeyFromInputActionName_ReturnValue_1) == 0x0000C0, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_GetKeyFromInputActionName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_Key_IsValid_ReturnValue) == 0x0000D8, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_Key_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, K2Node_Select_Default_1) == 0x0000E0, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(W_ReadyRoomWidget_C_UpdateInputActionTexts, CallFunc_FormatPlayerActionText_ReturnValue_1) == 0x0000F8, "Member 'W_ReadyRoomWidget_C_UpdateInputActionTexts::CallFunc_FormatPlayerActionText_ReturnValue_1' has a wrong offset!");

}

