#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TeamView

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_TeamView.W_TeamView_C
// 0x0028 (0x0510 - 0x04E8)
class UW_TeamView_C final : public UTeamViewWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 CloseView_ProgressCircle_Image;                    // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInvalidationBox*                       InvalidationBox;                                   // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           TeamView_Data;                                     // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MID_ProgressCircle;                                // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_W_TeamView(int32 EntryPoint);
	void Tick_TeamViewOn();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_TeamView_C">();
	}
	static class UW_TeamView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_TeamView_C>();
	}
};
static_assert(alignof(UW_TeamView_C) == 0x000008, "Wrong alignment on UW_TeamView_C");
static_assert(sizeof(UW_TeamView_C) == 0x000510, "Wrong size on UW_TeamView_C");
static_assert(offsetof(UW_TeamView_C, UberGraphFrame) == 0x0004E8, "Member 'UW_TeamView_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_TeamView_C, CloseView_ProgressCircle_Image) == 0x0004F0, "Member 'UW_TeamView_C::CloseView_ProgressCircle_Image' has a wrong offset!");
static_assert(offsetof(UW_TeamView_C, InvalidationBox) == 0x0004F8, "Member 'UW_TeamView_C::InvalidationBox' has a wrong offset!");
static_assert(offsetof(UW_TeamView_C, TeamView_Data) == 0x000500, "Member 'UW_TeamView_C::TeamView_Data' has a wrong offset!");
static_assert(offsetof(UW_TeamView_C, MID_ProgressCircle) == 0x000508, "Member 'UW_TeamView_C::MID_ProgressCircle' has a wrong offset!");

}

