#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TutorialMissionButton

#include "Basic.hpp"

#include "ReadyOrNot_structs.hpp"
#include "Engine_structs.hpp"
#include "W_StandardButton_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_TutorialMissionButton.W_TutorialMissionButton_C
// 0x0308 (0x08C0 - 0x05B8)
class UW_TutorialMissionButton_C final : public UW_StandardButton_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_TutorialMissionButton_C;          // 0x05B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FTutorialMissionData                   TutorialData;                                      // 0x05C0(0x0300)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void Construct();
	void Destruct();
	void ExecuteUbergraph_W_TutorialMissionButton(int32 EntryPoint);
	void UpdateTutorialMissionData(class UW_StandardButton_C* CallingButton);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_TutorialMissionButton_C">();
	}
	static class UW_TutorialMissionButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_TutorialMissionButton_C>();
	}
};
static_assert(alignof(UW_TutorialMissionButton_C) == 0x000008, "Wrong alignment on UW_TutorialMissionButton_C");
static_assert(sizeof(UW_TutorialMissionButton_C) == 0x0008C0, "Wrong size on UW_TutorialMissionButton_C");
static_assert(offsetof(UW_TutorialMissionButton_C, UberGraphFrame_W_TutorialMissionButton_C) == 0x0005B8, "Member 'UW_TutorialMissionButton_C::UberGraphFrame_W_TutorialMissionButton_C' has a wrong offset!");
static_assert(offsetof(UW_TutorialMissionButton_C, TutorialData) == 0x0005C0, "Member 'UW_TutorialMissionButton_C::TutorialData' has a wrong offset!");

}

